## =============================================================================
## R-02_precipitation_processing.R
##
## Purpose : (1) Process raw daily precipitation data into annual winter
##               totals with lagged values (WPy0 through WPy0-6) using the
##               Montgomery Field station as the regional proxy.
##               Generates data/cleaned/precipyrs.csv used by R-03 through R-08.
##
##           (2) Test whether precipitation variance is primarily temporal or
##               spatial using a two-way ANOVA (precipitation ~ station + year)
##               across all stations. Confirms that interannual variation
##               dominates over among-station variation, justifying use of a
##               single station as the regional precipitation proxy.
##
##           (3) Test for temporal autocorrelation in winter precipitation
##               across lags 1–5 years (ACF/PACF). No significant correlations
##               confirm that annual precipitation values can be treated as
##               independent observations in downstream models.
##
## Inputs  : data/raw/sd_station_prcp.csv  — daily PRCP for all SD-area NWS
##                                           stations (columns: STATION, NAME,
##                                           DATE, PRCP in mm)
##           data/raw/site_stations.csv    — plot-to-station assignments
##                                           (generated by R-00_station_setup.R;
##                                           needed for station map only)
##
## Outputs : data/cleaned/precipyrs.csv            — annual winter totals + lags
##           figures/monthly_heatmap.png            — monthly precip heatmap
##           figures/acf_scf.png                   — ACF/PACF plot (Fig. S4)
##           figures/stations_precip.png           — annual precip by station (Fig. S3)
##           figures/stations_map.png              — map of plots and stations (Fig. S2)
##           figures/Figure1.pdf                   — precipitation bar graph (Fig. 1B)
##           results/Table_S2_ANOVA_precip.xlsx    — temporal vs spatial ANOVA
##
## Author  : [Your name]
## Date    : [Date]
## =============================================================================

# ---- packages ----
library(dplyr)
library(lubridate)
library(ggplot2)
library(tidyr)
library(car)
library(broom)
library(writexl)
library(ggmap)
library(ggrepel)
library(RColorBrewer)

## File paths
figures_dir <- "figures"
results_dir <- "results"
cleaned_dir <- "data/cleaned"
raw_dir     <- "data/raw"

## Station name constant
MONTGOMERY <- "SAN DIEGO MONTGOMERY FIELD, CA US"

# =============================================================================
# SECTION 1 — Load and parse all station data
# =============================================================================

sd_prcp <- read.csv(file.path(raw_dir, "sd_station_prcp.csv"),
                    stringsAsFactors = FALSE) %>%
  mutate(
    DATE  = ymd(DATE),
    PRCP_mm  = as.numeric(PRCP) * 25.4,   # inches → mm,
    year  = year(DATE),
    mo    = month(DATE),
    month = month(DATE, label = TRUE, abbr = TRUE)
  )

# Montgomery Field record only — used for annual totals, heatmap, ACF
precip_manual <- sd_prcp %>%
  filter(NAME == MONTGOMERY)

# =============================================================================
# SECTION 2 — Monthly heatmap (diagnostic)
# =============================================================================

monthly_precip <- precip_manual %>%
  group_by(year, month) %>%
  summarise(total_prcp = sum(PRCP_mm, na.rm = TRUE), .groups = "drop") %>%
  filter(year >= 1999)

ggplot(monthly_precip, aes(x = month, y = factor(year), fill = total_prcp)) +
  geom_tile(color = "white") +
  scale_fill_viridis_c(option = "C", name = "Monthly\nPrecip (mm)") +
  labs(x = "Month", y = "Year",
       title    = "Monthly Precipitation (1999–2024)",
       subtitle = "Montgomery Field Air Station") +
  theme_minimal(base_size = 14) +
  theme(axis.text.y = element_text(size = 7))

ggsave(file.path(figures_dir, "monthly_heatmap.png"),
       width = 8, height = 8, dpi = 300)

# =============================================================================
# SECTION 3 — Annual winter totals + lags (Montgomery Field)
#
# Nov 2010–Mar 2011 is assigned to winter year 2011.
# PRCP is already in mm.
# =============================================================================

precip_winter <- precip_manual %>%
  mutate(
    winter_year = year + if_else(mo >= 11L, 1L, 0L)
  ) %>%
  filter(mo %in% c(11, 12, 1, 2, 3))

precipitation_yearly <- precip_winter %>%
  group_by(year = winter_year) %>%
  summarize(same = sum(PRCP_mm, na.rm = TRUE), .groups = "drop") %>%
  arrange(year) %>%
  mutate(
    previous1 = dplyr::lag(same, 1),
    previous2 = dplyr::lag(same, 2),
    previous3 = dplyr::lag(same, 3),
    previous4 = dplyr::lag(same, 4),
    previous5 = dplyr::lag(same, 5),
    previous6 = dplyr::lag(same, 6)
  )

write.csv(precipitation_yearly,
          file.path(cleaned_dir, "precipyrs.csv"),
          row.names = FALSE)

average_precipitation <- mean(precipitation_yearly$same, na.rm = TRUE)

# =============================================================================
# SECTION 4 — Temporal vs. spatial variance in precipitation (Table S2)
#
# Two-way ANOVA: winter_precip ~ station + year across all stations.
# Tests whether interannual variation (temporal) explains more variance
# than among-station variation (spatial), justifying use of a single
# regional station as the precipitation proxy.
# =============================================================================

l_noplots <- c("SWS10","CrCyn","MTLA","SWI1","MTS1A-Urb",
               "UCSDN","TRR1","TRS1","SCR")

# Build station-level annual winter totals from all stations
station_yearly <- sd_prcp %>%
  filter(!NAME == "SAN DIEGO MIRAMAR NAS, CA US") %>% # missing data
  mutate(winter_year = year + if_else(mo >= 11L, 1L, 0L)) %>%
  filter(mo %in% c(11, 12, 1, 2, 3),
         year >= 2000) %>%
  group_by(NAME, year = winter_year) %>%
  summarise(same_precip = sum(PRCP_mm, na.rm = TRUE), .groups = "drop") %>%
  filter(year >= 2000, year <= 2024)

# ANOVA
precip_aov <- aov(same_precip ~ factor(NAME) + factor(year),
                  data = station_yearly)
summary(precip_aov)
car::Anova(precip_aov, type = 3)

# Residual diagnostics
par(mfrow = c(2, 2))
plot(precip_aov)
par(mfrow = c(1, 1))

# Export results
writexl::write_xlsx(broom::tidy(precip_aov),
                    file.path(results_dir, "Table_S2_ANOVA_precip.xlsx"))

# =============================================================================
# SECTION 5 — Autocorrelation test (Fig. S4)
#
# ACF and PACF on the Montgomery Field annual winter record.
# No significant correlations = years treated as independent in models.
# =============================================================================

montgomery <- precipitation_yearly %>%
  filter(year >= 2000, year <= 2024) %>%
  arrange(year)

x <- montgomery$same
n <- sum(!is.na(x))

# Lag correlation table
precip_df <- tibble::tibble(
  year = montgomery$year,
  same = x,
  lag1 = dplyr::lag(x, 1),
  lag2 = dplyr::lag(x, 2),
  lag3 = dplyr::lag(x, 3),
  lag4 = dplyr::lag(x, 4),
  lag5 = dplyr::lag(x, 5)
)

lag_corrs <- sapply(1:5, function(l) {
  cor(precip_df$same, dplyr::pull(precip_df, paste0("lag", l)),
      use = "pairwise.complete.obs")
})
lag_corrs

# ACF + PACF
acf_vals  <- acf(x,  lag.max = 5, plot = FALSE)$acf
pacf_vals <- pacf(x, lag.max = 5, plot = FALSE)$acf

acf_pacf_tbl <- tibble::tibble(
  lag  = 1:5,
  ACF  = round(acf_vals[2:6], 3),
  PACF = round(pacf_vals[1:5], 3)
)
print(acf_pacf_tbl)

sig_bound <- 2 / sqrt(n)

acf_fig <- acf_pacf_tbl %>%
  pivot_longer(cols = c(ACF, PACF), names_to = "Type", values_to = "Correlation") %>%
  ggplot(aes(x = factor(lag), y = Correlation, fill = Type)) +
  geom_col(position = "dodge", width = 0.6) +
  geom_hline(yintercept = 0, color = "black") +
  geom_hline(yintercept = c(-sig_bound, sig_bound),
             linetype = "dashed", color = "blue") +
  scale_fill_manual(values = c("ACF" = "skyblue3", "PACF" = "tan3")) +
  labs(
    title    = "Autocorrelation of Winter Precipitation — Montgomery Field",
    subtitle = sprintf("95%% significance bounds (±%.2f), n = %d", sig_bound, n),
    x = "Lag (years)", y = "Correlation"
  ) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "bottom")

ggsave(file.path(figures_dir, "acf_scf.png"),
       acf_fig, width = 6, height = 4, dpi = 300)

# =============================================================================
# SECTION 6 — Annual precipitation by station (Fig. S3)
# =============================================================================

station_levels <- sort(unique(station_yearly$NAME))
make_palette   <- colorRampPalette(brewer.pal(8, "Set3"))
n_other        <- max(length(station_levels) - 1, 1)
other_colors   <- make_palette(n_other)
names(other_colors) <- setdiff(station_levels, MONTGOMERY)
color_vector   <- c(other_colors, setNames("orange", MONTGOMERY))

stns_plot <- ggplot(station_yearly,
                    aes(x = year, y = same_precip,
                        color = NAME, group = NAME)) +
  geom_line(linewidth = 0.8) +
  geom_point(size = 2) +
  scale_color_manual(values = color_vector) +
  labs(
    title    = "Annual Winter Precipitation by Weather Station (Nov–Mar)",
    subtitle = "Montgomery Field highlighted in orange",
    x = "Year", y = "Precipitation (mm)", color = "Station"
  ) +
  theme_minimal(base_size = 14) +
  theme(legend.position  = "bottom",
        legend.title     = element_text(face = "bold"),
        panel.grid.minor = element_blank())

ggsave(file.path(figures_dir, "stations_precip.png"),
       stns_plot, width = 8, height = 6, dpi = 300)

# =============================================================================
# SECTION 7 — Map of study plots and weather stations (Fig. S2)
#
# Requires a free Stadia Maps API key: https://stadiamaps.com/
# Do not commit your key to GitHub.
# =============================================================================

register_stadiamaps(key = "GET YOUR OWN API KEY :)")

site_stations <- read.csv(file.path(raw_dir, "site_stations.csv"))

plot_points <- site_stations %>%
  distinct(fieldNumber, Type, Latitude, Longitude) %>%
  mutate(PointType = Type, label = fieldNumber)

station_coords <- tibble::tibble(
  NAME      = c(
    "SAN DIEGO MONTGOMERY FIELD, CA US",
    "CHULA VISTA, CA US",
    "SAN DIEGO INTERNATIONAL AIRPORT, CA US",
    "SAN DIEGO SEAWORLD, CA US",
    "EL CAJON, CA US",
    "SAN DIEGO MIRAMAR NAS, CA US"
  ),
  Latitude  = c(32.81444, 32.6400, 32.73361, 32.7631, 32.7384, 32.8711),
  Longitude = c(-117.13639, -117.0800, -117.18306, -117.2299, -116.91, -117.1719)
)

weather_points <- station_coords %>%
  transmute(
    Latitude  = Latitude,
    Longitude = Longitude,
    PointType = ifelse(NAME == MONTGOMERY, "Montgomery Field", "Weather Station"),
    label     = NA_character_
  )

map_points <- bind_rows(
  plot_points %>% select(Latitude, Longitude, PointType, label),
  weather_points
)

buffer <- 0.02
bbox <- c(
  left   = min(map_points$Longitude, na.rm = TRUE) - buffer,
  bottom = min(map_points$Latitude,  na.rm = TRUE) - buffer,
  right  = max(map_points$Longitude, na.rm = TRUE) + buffer,
  top    = max(map_points$Latitude,  na.rm = TRUE) + buffer
)

sd_map <- get_stadiamap(bbox = bbox, zoom = 11,
                        maptype = "stamen_terrain_background")

mappy <- ggmap(sd_map, darken = c(0.4, "white")) +
  geom_point(
    data = map_points,
    aes(x = Longitude, y = Latitude, shape = PointType, color = PointType),
    size = 3, stroke = 1
  ) +
  geom_text_repel(
    data = filter(map_points, PointType %in% c("Fragment", "Reserve")),
    aes(x = Longitude, y = Latitude, label = label),
    size = 3, box.padding = 0.3, point.padding = 0.2,
    max.overlaps = Inf, show.legend = FALSE
  ) +
  scale_shape_manual(values = c("Fragment"         = 16, "Reserve"          = 16,
                                "Weather Station"  = 17, "Montgomery Field" = 17)) +
  scale_color_manual(values = c("Fragment"         = "gray52",
                                "Reserve"          = "springgreen4",
                                "Weather Station"  = "blue",
                                "Montgomery Field" = "orange")) +
  labs(title    = "Sampling plots and weather stations",
       subtitle = "Coastal San Diego County",
       x = "Longitude", y = "Latitude",
       color = "Type", shape = "Type") +
  theme_minimal() +
  theme(legend.position = "bottom")

ggsave(file.path(figures_dir, "stations_map.png"),
       mappy, width = 6, height = 6, dpi = 300)

# =============================================================================
# SECTION 8 — Precipitation bar graph (Fig. 1B)
# =============================================================================

survey_years <- c(2011, 2012, 2015, 2016, 2022, 2023, 2024)

pdat <- precipitation_yearly %>%
  transmute(
    year      = as.integer(year),
    precip    = same,
    year_type = if_else(year %in% survey_years, "Survey year", "Non-survey year")
  ) %>%
  filter(year >= 2010, year <= 2024)

stats_25_ci <- precipitation_yearly %>%
  filter(year >= 2000, year <= 2024) %>%
  summarise(
    n       = sum(!is.na(same)),
    mean_p  = mean(same, na.rm = TRUE),
    sd_p    = sd(same,   na.rm = TRUE),
    se_p    = sd_p / sqrt(n),
    ci_low  = mean_p - qt(0.975, df = n - 1) * se_p,
    ci_high = mean_p + qt(0.975, df = n - 1) * se_p
  )

conf95 <- ggplot(pdat,
                 aes(x = factor(year), y = precip, fill = year_type)) +
  geom_col(width = 0.82) +
  geom_rect(data = stats_25_ci,
            aes(xmin = -Inf, xmax = Inf, ymin = ci_low, ymax = ci_high),
            inherit.aes = FALSE, fill = "grey70", alpha = 0.25) +
  geom_hline(aes(yintercept = mean_p), data = stats_25_ci,
             linewidth = 1.0, linetype = "dashed", color = "grey20") +
  geom_hline(aes(yintercept = ci_low),  data = stats_25_ci,
             linetype = "dotted", color = "grey20") +
  geom_hline(aes(yintercept = ci_high), data = stats_25_ci,
             linetype = "dotted", color = "grey20") +
  scale_fill_manual(
    values = c("Non-survey year" = "grey80", "Survey year" = "grey35"),
    name   = NULL
  ) +
  labs(x = NULL, y = "Winter precipitation (mm)") +
  theme_classic(base_size = 13) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave(file.path(figures_dir, "Figure1.pdf"),
       conf95, width = 173, height = 100, units = "mm")
