## =============================================================================
## R-03_primary_production.R
##
## Purpose : Test Prediction 1 — primary production (EVI) increases with
##           same-year winter precipitation (WPy0). Fits a linear regression
##           of mean summer EVI on total winter precipitation over a 25-year
##           period (2000–2024).
##
## Inputs  : data/cleaned/precipyrs.csv  — annual winter totals + lags
##                                         (generated by R-02; column: same)
##           data/raw/wild_evi.csv       — MODIS EVI values (from GEE;
##                                         columns: year, mean_EVI)
##
## Outputs : figures/evi_plot.svg        — EVI ~ precipitation scatter (Fig. 2)
##           Console: model summary, R², assumption diagnostics
##
## Author  : Jess Mullins
## Date    : 6-Apr-2026
## =============================================================================

library(ggplot2)
library(dplyr)
library(car)
library(lmtest)
library(ggfortify)
library(MASS)

## File paths
figures_dir <- "figures"
results_dir <- "results"
cleaned_dir <- "data/cleaned"
raw_dir     <- "data/raw"

# =============================================================================
# SECTION 1 — Load and merge data
# =============================================================================

precip <- read.csv(file.path(cleaned_dir, "precipyrs.csv"))
evi    <- read.csv(file.path(raw_dir,     "wild_evi.csv"))

# Join on year; use same-year precipitation (WPy0 = same)
merged_data <- left_join(evi, precip %>% select(year, same), by = "year")

# =============================================================================
# SECTION 2 — Linear model: EVI ~ same-year winter precipitation
# =============================================================================

evi_lm <- lm(mean_EVI ~ same, data = merged_data)
summary(evi_lm)
car::Anova(evi_lm)

r2_val <- summary(evi_lm)$r.squared
p_val  <- summary(evi_lm)$coefficients[2, 4]

# =============================================================================
# SECTION 3 — Figure
# =============================================================================

evi_plot <- ggplot(merged_data, aes(x = same, y = mean_EVI)) +
  geom_point(shape = 21, fill = "black", color = "white",
             size = 4, stroke = 0.4, alpha = 0.8) +
  geom_smooth(method = "lm", se = TRUE,
              color = "gray50", fill = "gray80", linewidth = 0.70) +
  labs(x = "Winter precipitation (mm)",
       y = "Mean summer EVI") +
  theme_classic(base_size = 13)

print(evi_plot)

ggsave(file.path(figures_dir, "evi_plot.svg"),
       plot = evi_plot, width = 5, height = 5.2, units = "in")

# =============================================================================
# SECTION 4 — Assumption diagnostics
# =============================================================================

# Linearity and homoscedasticity
plot(evi_lm$fitted.values, resid(evi_lm),
     xlab = "Fitted values", ylab = "Residuals",
     main = "Residuals vs Fitted")
abline(h = 0, col = "red")

# Normality of residuals
hist(resid(evi_lm), main = "Histogram of residuals", xlab = "Residuals")

qqnorm(resid(evi_lm))
qqline(resid(evi_lm), col = "red")

shapiro.test(resid(evi_lm))

# Influential observations
plot(cooks.distance(evi_lm), type = "h",
     main = "Cook's Distance", ylab = "Cook's Distance")
abline(h = 4 / (nrow(merged_data) - length(evi_lm$coefficients) - 2),
       col = "red")

plot(hatvalues(evi_lm), main = "Leverage", ylab = "Leverage")
