## =============================================================================
## R-04_floral_richness.R
##
## Purpose : Test Prediction 1 (supplementary) — floral species richness
##           differs between site types and across years of contrasting
##           precipitation. Mixed-effects model with site type × year
##           interaction across five survey years (2015, 2016, 2022, 2023,
##           2024). Also tests EVI as a predictor of floral richness.
##
## Inputs  : data/raw/all_plants.csv       — plant occurrence records; curated
##                                           from field surveys and iNaturalist
##                                           observations. Plants from 2022–2024
##                                           are available at:
##                                           https://www.inaturalist.org/projects/sd-fragment-reserve-resurvey
##                                           Raw iNaturalist export not provided;
##                                           use all_plants.csv for reproducibility.
##           data/raw/siteInfo.csv         — plot-level metadata
##           data/cleaned/precipyrs.csv    — annual winter totals + lags
##                                           (generated by R-02)
##           data/raw/wild_evi.csv         — MODIS EVI (from GEE)
##
## Outputs : figures/floral_richness.svg          — richness by year + site type
##           results/plant_models_results.xlsx     — model summaries, ANOVA,
##                                                   emmeans contrasts
##
## Author  : [Your name]
## Date    : [Date]
## =============================================================================

library(dplyr)
library(tibble)
library(readr)
library(forcats)
library(lme4)
library(lmerTest)
library(emmeans)
library(performance)
library(influence.ME)
library(car)
library(ggplot2)
library(openxlsx)

## File paths
figures_dir <- "figures"
results_dir <- "results"
cleaned_dir <- "data/cleaned"
raw_dir     <- "data/raw"

# =============================================================================
# SECTION 1 — Load and prepare data
# =============================================================================

all_plants <- read_csv(file.path(raw_dir, "all_plants.csv"),
                       show_col_types = FALSE)
plots_raw  <- read_csv(file.path(raw_dir, "siteInfo.csv"),
                       show_col_types = FALSE)
evi        <- read_csv(file.path(raw_dir, "wild_evi.csv"),
                       show_col_types = FALSE)

survey_years <- c(2015, 2016, 2022, 2023, 2024)

dat <- all_plants %>%
  left_join(plots_raw, by = c("plot" = "fieldNumber")) %>%
  filter(!is.na(sp.code),
         !plot %in% c("SWS10", "SCR"),
         !is.na(plot),
         !is.na(year))

# =============================================================================
# SECTION 2 — Calculate mean floral richness per plot-year
#
# Survey days are standardized per year to account for unequal effort.
# Mean richness = mean number of unique species observed per survey visit.
# =============================================================================

survey_days <- dat %>%
  group_by(plot, year) %>%
  summarise(survey_days = n_distinct(date), .groups = "drop") %>%
  mutate(survey_days = case_when(
    year == 2022 ~ 8,
    year == 2023 ~ 6,
    year == 2024 ~ 6,
    TRUE ~ survey_days
  ))

sp_per_date <- dat %>%
  group_by(plot, year, date, Type) %>%
  summarise(unique_sp = n_distinct(sp.code), .groups = "drop")

sp_per_plot_year <- sp_per_date %>%
  group_by(plot, year, Type) %>%
  summarise(mean_richness = mean(unique_sp), .groups = "drop") %>%
  left_join(survey_days, by = c("plot", "year")) %>%
  mutate(
    survey_days_sc = as.numeric(scale(survey_days)),
    Type           = fct_relevel(Type, "Reserve", "Fragment")
  )

# =============================================================================
# SECTION 3 — Model: richness ~ site type × year (2015, 2016, 2022–2024)
# =============================================================================

plot_dat <- sp_per_plot_year %>%
  filter(year %in% survey_years) %>%
  mutate(year_f = factor(year, levels = survey_years))

# Figure
p_richness <- ggplot(plot_dat, aes(x = year_f, y = mean_richness)) +
  geom_boxplot(aes(fill = Type),
               outlier.shape = NA, width = 0.6, color = "gray40",
               position = position_dodge2(width = 0.65, preserve = "single")) +
  scale_fill_manual(values = c(Reserve = "#2C7C4D", Fragment = "#BDBDBD")) +
  scale_y_continuous(name = "Mean floral species richness") +
  labs(x = "", fill = "Study site type") +
  theme_classic(base_size = 13) +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor   = element_blank(),
        legend.position    = "right",
        axis.text.x        = element_text(angle = 45, hjust = 1))

print(p_richness)

ggsave(file.path(figures_dir, "floral_richness.svg"),
       plot = p_richness, width = 5.2, height = 5, units = "in")

# Model
m_richness <- lmer(mean_richness ~ Type * year_f + (1 | plot),
                   data = plot_dat)

summary(m_richness)
car::Anova(m_richness, type = "3")

# Assumption checks
qqnorm(residuals(m_richness)); qqline(residuals(m_richness))
plot(m_richness)
isSingular(m_richness)
car::vif(m_richness)
performance::check_model(m_richness)

# Post-hoc contrasts
emmeans(m_richness, pairwise ~ Type | year_f)
emmeans(m_richness, pairwise ~ year_f | Type)

# =============================================================================
# SECTION 4 — Model: richness ~ site type × EVI
# =============================================================================

evi_clean <- evi %>%
  as.data.frame() %>%
  select(year, mean_EVI) %>%
  distinct(year, .keep_all = TRUE)

plot_dat_evi <- plot_dat %>%
  left_join(evi_clean, by = "year")

stopifnot(!anyNA(plot_dat_evi$mean_EVI))

m_evi <- lmer(mean_richness ~ Type * mean_EVI + (1 | plot),
              data = plot_dat_evi)

summary(m_evi)
car::Anova(m_evi, type = "III")

# =============================================================================
# SECTION 5 — Export model results
# =============================================================================

tidy_lmer <- function(mod) {
  as.data.frame(coef(summary(mod))) %>%
    rownames_to_column("Term")
}

wb <- createWorkbook()

addWorksheet(wb, "Richness_Summary")
writeData(wb, "Richness_Summary", tidy_lmer(m_richness))

addWorksheet(wb, "Richness_Anova")
writeData(wb, "Richness_Anova", as.data.frame(car::Anova(m_richness, type = "III")))

addWorksheet(wb, "Richness_Emmeans_Year")
writeData(wb, "Richness_Emmeans_Year",
          as.data.frame(emmeans(m_richness, pairwise ~ year_f | Type)$contrasts))

addWorksheet(wb, "Richness_Emmeans_Type")
writeData(wb, "Richness_Emmeans_Type",
          as.data.frame(emmeans(m_richness, pairwise ~ Type | year_f)$contrasts))

addWorksheet(wb, "EVI_Summary")
writeData(wb, "EVI_Summary", tidy_lmer(m_evi))

addWorksheet(wb, "EVI_Anova")
writeData(wb, "EVI_Anova", as.data.frame(car::Anova(m_evi, type = "III")))

saveWorkbook(wb, file.path(results_dir, "plant_models_results.xlsx"),
             overwrite = TRUE)
