## =============================================================================
## R-05_bee_diversity.R
##
## Purpose : Test Prediction 2 — bee diversity increases with winter
##           precipitation. Coverage-standardized Hill numbers (q=0,1,2)
##           via iNEXT::estimateD() at the shared coverage target from R-01.
##           Mixed-effects models with WPy0, WPy0-1, site type, and
##           interactions. AIC model comparison; marginal R² via MuMIn.
##           Main analysis (coverage-standardized; not sensitivity rarefaction).
##
## Inputs  : data/cleaned/df_analysis.csv       — filtered occurrence records
##                                                 (generated by R-01)
##           data/cleaned/target_coverage.rds   — shared coverage target scalar
##                                                 (generated by R-01)
##           data/cleaned/precipyrs.csv         — annual winter totals + lags
##                                                 (generated by R-02)
##
## Outputs : figures/Fig_diversity_coverage_*.svg
##           results/Richness_model_results.xlsx
##           results/HillShannon_model_results.xlsx
##           results/HillSimpson_model_results.xlsx
##
## Author  : Jess Mullins
## Date    : 6-April-2026
## =============================================================================

#### =========================================
#### Bee diversity: coverage-standardized Hill numbers
#### =========================================

#### 0) Packages ####
suppressPackageStartupMessages({
  library(tidyverse)
  library(vegan)
  library(iNEXT)
  library(lme4)
  library(lmerTest)
  library(car)
  library(performance)
  library(forcats)
  library(patchwork)
  library(ggeffects)
  library(broom)
  library(broom.mixed)
  library(writexl)
  library(MuMIn)
  library(DHARMa)
  library(MASS)
})

## File paths
figures_dir <- "figures"
results_dir <- "results"
cleaned_dir <- "data/cleaned"
raw_dir     <- "data/raw"

#### 1) Load data ####

# Occurrence records cleaned by R-01
df_analysis <- read.csv(file.path(cleaned_dir, "df_analysis.csv"))

# Shared coverage target computed by R-01 — ensures identical standardization
# across all analyses (diversity, RDA, body size)
target_cov <- readRDS(file.path(cleaned_dir, "target_coverage.rds"))
cat("Loaded target coverage from R-01:", round(target_cov, 4), "\n")

# Precipitation with lags from R-02
precipitation_yearly <- read.csv(file.path(cleaned_dir, "precipyrs.csv")) %>%
  drop_na()

indicators <- c("Halictus farinosus", "Lasioglossum sisymbrii",
                "Augochlorella pomoniella", "Eucera dorsata", "Eucera tricinctella",
                "Lasioglossum punctatoventre", "Lasioglossum robustum",
                "Megachile subnigra", "Melissodes plumosus", "Anthidium jocosum",
                "Ceratina nanula", "Lasioglossum MSN turgiventre",
                "Lasioglossum perparvum", "Melissodes tessellatus",
                "Micralictoides ruficaudus", "Andrena osmioides",
                "Perdita interrupta interrupta", "Dianthidium dubium",
                "Dufourea sandhouseae", "Andrena ablegata",
                "Dianthidium pudicum consimile", "Megachile coquilletti",
                "Osmia gabrielis", "Anthophorula torticornis", "Bombus vosnesenskii",
                "Lasioglossum titusi", "Lasioglossum actinosum",
                "Lasioglossum stictaspis complex", "Osmia granulosa",
                "Halictus ligatus", "Bombus californicus", "Osmia clarescens",
                "Hylaeus mesillae cressoni", "Diadasia opuntiae",
                "Calliopsis obscurella", "Hesperapis fuchsi", "Melissodes stearnsi",
                "Ashmeadiella californica", "Dufourea rhamni", "Andrena atypica",
                "Lasioglossum perichlarum", "Megachile onobrychidis",
                "Dufourea brevicornis", "Melissodes velutinus", "Diadasia ochracea",
                "Perdita claypolei australior")

# Precipitation means for centering
precipitation_yearly$year <- as.factor(precipitation_yearly$year)
mean_same  <- mean(precipitation_yearly$same,      na.rm = TRUE)
mean_prev  <- mean(precipitation_yearly$previous1, na.rm = TRUE)
mean_prev2 <- mean(precipitation_yearly$previous2, na.rm = TRUE)

#### 2) Coverage-standardized Hill numbers (q = 0,1,2) ####

# 2.1 Build wide species-by-sample matrix from df_analysis
# df_analysis uses fieldNumber; rename to Plot for consistency with downstream code
allbees <- df_analysis %>%
  rename(Plot = fieldNumber) %>%
  mutate(
    year      = factor(year, levels = survey_years),
    Count     = as.numeric(individualCount),
    plot_year = paste(Plot, year, sep = "_")
  ) %>%
  filter(
  #  !scientificName  %in% indicators,  # remove to test indicator species effect
  )

comm <- allbees %>%
  group_by(plot_year, Plot, year, Type, scientificName) %>%
  summarise(n = sum(Count), .groups = "drop") %>%
  pivot_wider(names_from = scientificName, values_from = n, values_fill = 0)

meta <- comm %>%
  dplyr::select(plot_year, Plot, year, Type)

species_cols <- setdiff(names(comm), c("plot_year","Plot","year","Type"))

# Turn each row into a vector of positive counts for iNEXT
abund_list <- apply(
  comm[, species_cols, drop = FALSE],
  1,
  function(z) {
    z <- as.numeric(z)
    z[z > 0]
  }
)
names(abund_list) <- comm$plot_year

# 2.2 Estimate Hill numbers at shared coverage target from R-01
# target_cov loaded above — same value used for RDA and body size analyses
est <- iNEXT::estimateD(
  abund_list,
  q        = c(0, 1, 2),
  datatype = "abundance",
  base     = "coverage",
  level    = target_cov
) %>%
  as_tibble()

# 2.4 Long coverage dataset
long_cov <- est %>%
  transmute(
    plot_year = Assemblage,
    Order.q,
    SC,
    qD
  ) %>%
  left_join(meta, by = "plot_year") %>%
  mutate(
    Metric = dplyr::recode(
      Order.q,
      `0` = "Richness",
      `1` = "Hill_Shannon",
      `2` = "Hill_Simpson"
    ),
    Method = paste0("Coverage (common SC = ", round(SC[1], 2), ")")
  ) %>%
  dplyr::select(
    Plot, Type, year, plot_year, Metric,
    Value = qD,
    common_coverage = SC, Method
  )

# 2.5 Join precipitation + center
long_cov <- long_cov %>%
  left_join(
    precipitation_yearly %>%
      dplyr::select(year, same, previous1, previous2),
    by = "year"
  ) %>%
  mutate(
    same_c      = same      - mean_same,
    previous1_c = previous1 - mean_prev,
    previous2_c = previous2 - mean_prev2
  )

# Main working dataset
long_data <- long_cov

# Colors and helper 
col_vals   <- c(Reserve = "#2C7C4D", Fragment = "#BDBDBD")
shape_vals <- c(Reserve = 15,       Fragment = 16)  # 15 = filled square, 16 = filled circle


get_r2 <- function(m) {
  r2 <- suppressWarnings(MuMIn::r.squaredGLMM(m))
  c(R2m = as.numeric(r2[1, "R2m"]), R2c = as.numeric(r2[1, "R2c"]))
}

#### 3) Richness (q = 0) ####

# 3.1 Subset data
dd_rich <- long_data %>%
  filter(Metric == "Richness") %>%
  drop_na(Value, Plot, Type, same, previous1, same_c, previous1_c) %>%
  mutate(Type = forcats::fct_relevel(Type, "Reserve", "Fragment"))

# 3.2 Model formulas
form_rich_prev  <- Value ~ Type * previous1_c + (1 | Plot)
form_rich_same  <- Value ~ Type * same_c      + (1 | Plot)
form_rich_full  <- Value ~ Type * previous1_c + Type * same_c + (1 | Plot)

# 3.3 Fit models with ML for AIC
m_rich_prev_ml <- lmer(form_rich_prev, data = dd_rich, REML = FALSE)
m_rich_same_ml <- lmer(form_rich_same, data = dd_rich, REML = FALSE)
m_rich_full_ml <- lmer(form_rich_full, data = dd_rich, REML = FALSE)

aic_rich <- tibble(
  model   = c("prev_only", "same_only", "prev+same"),
  formula = c(
    deparse(form_rich_prev),
    deparse(form_rich_same),
    deparse(form_rich_full)
  ),
  AIC     = c(
    AIC(m_rich_prev_ml),
    AIC(m_rich_same_ml),
    AIC(m_rich_full_ml)
  )
) %>%
  arrange(AIC)

print(aic_rich)

# 3.4 Refit models with REML for inference
m_rich_prev_reml <- lmer(form_rich_prev, data = dd_rich, REML = TRUE)
m_rich_same_reml <- lmer(form_rich_same, data = dd_rich, REML = TRUE)
m_rich_full_reml <- lmer(form_rich_full, data = dd_rich, REML = TRUE)

# Type III ANOVA for full model
anova_rich_full <- car::Anova(m_rich_full_reml, type = "III")
print(anova_rich_full)

# R2 (Nakagawa) for full model
r2_rich_full <- performance::r2_nakagawa(m_rich_full_reml)
print(r2_rich_full)
summary(m_rich_full_reml )
# Fixed effects (CIs) and glance
coef_rich_full <- broom.mixed::tidy(
  m_rich_full_reml,
  effects = "fixed",
  conf.int = TRUE
)
print(coef_rich_full)

glance_rich_full <- broom.mixed::glance(m_rich_full_reml)
print(glance_rich_full)

# 3.5 R2 comparison across models
r2_mat_rich <- rbind(
  get_r2(m_rich_prev_reml),
  get_r2(m_rich_same_reml),
  get_r2(m_rich_full_reml)
)

r2_table_rich <- tibble(
  model          = c("prev_only", "same_only", "prev+same"),
  formula        = c(
    deparse(form_rich_prev),
    deparse(form_rich_same),
    deparse(form_rich_full)
  ),
  R2_marginal    = r2_mat_rich[, "R2m"],
  R2_conditional = r2_mat_rich[, "R2c"]
)

rich_m <- r2_table_rich$R2_marginal[r2_table_rich$model == "prev+same"]
rich_c <- r2_table_rich$R2_conditional[r2_table_rich$model == "prev+same"]

r2_table_rich <- r2_table_rich %>%
  mutate(
    dR2m_vs_full = R2_marginal    - rich_m,
    dR2c_vs_full = R2_conditional - rich_c
  )

print(r2_table_rich)

# 3.6 Assumption checks — see Section 6 (consolidated diagnostics)

# 3.7 Model-based plots for Richness

# Previous-year effect (same_c = 0)
pred_rich_prev <- ggpredict(
  m_rich_full_reml,
  terms     = c("previous1_c [all]", "Type"),
  condition = list(same_c = 0)
) %>%
  as.data.frame() %>%
  mutate(x_mm = x + mean(dd_rich$previous1, na.rm = TRUE))

# Same-year effect (previous1_c = 0)
pred_rich_same <- ggpredict(
  m_rich_full_reml,
  terms     = c("same_c [all]", "Type"),
  condition = list(previous1_c = 0)
) %>%
  as.data.frame() %>%
  mutate(x_mm = x + mean(dd_rich$same, na.rm = TRUE))

p_rich_prev <- ggplot() +
  geom_point(
    data = dd_rich,
    aes(x = previous1, y = Value, color = Type, shape = Type),
    alpha = 0.35, size = 2
  ) +
  geom_ribbon(
    data = pred_rich_prev,
    aes(x = x_mm, ymin = conf.low, ymax = conf.high, fill = group),
    alpha = 0.25,
    show.legend = FALSE
  ) +
  geom_line(
    data = pred_rich_prev,
    aes(x = x_mm, y = predicted, color = group),
    linewidth = 1.2,
    show.legend = FALSE
  ) +
  scale_color_manual(values = col_vals, name = "Site type") +
  scale_shape_manual(values = shape_vals, name = "Site type") +
  scale_fill_manual(values = col_vals, guide = "none") +
  labs(
    x = NULL,   #  removes x-axis label
    y = "Richness (q = 0)"
  ) +
  theme_classic(base_size = 13) +
  theme(legend.position = "none")

p_rich_same <- ggplot() +
  geom_point(
    data = dd_rich,
    aes(x = same, y = Value, color = Type, shape = Type),
    alpha = 0.35, size = 2
  ) +
  geom_ribbon(
    data = pred_rich_same,
    aes(x = x_mm, ymin = conf.low, ymax = conf.high, fill = group),
    alpha = 0.25,
    show.legend = FALSE
  ) +
  geom_line(
    data = pred_rich_same,
    aes(x = x_mm, y = predicted, color = group),
    linewidth = 1.2,
    show.legend = FALSE
  ) +
  scale_color_manual(values = col_vals, name = "Site type") +
  scale_shape_manual(values = shape_vals, name = "Site type") +
  scale_fill_manual(values = col_vals, guide = "none") +
  labs(
    x = NULL,   #  removes x-axis label
    y = NULL
  ) +
  theme_classic(base_size = 13) +
  theme(legend.position = "none")  #  keeps ONLY ONE legend on the left plot


p_rich_model <- p_rich_prev + p_rich_same + plot_layout(ncol = 2)
print(p_rich_model)

ggsave(file.path(figures_dir, "p_Richness_coverage2.svg"), p_rich_model,
        width = 10, height = 4, units = "in", dpi = 600)

# 3.8 Export Richness results
sheets_rich <- list(
  AIC_table     = aic_rich,
  ANOVA_TypeIII = broom::tidy(anova_rich_full),
  Fixed_Effects = coef_rich_full,
  Model_Glance  = glance_rich_full,
  R2_models     = r2_table_rich
)

writexl::write_xlsx(
  sheets_rich,
  path = file.path(results_dir, "Richness_model_results_COVERAGE.xlsx")
)



#### 4) Hill_Shannon (q = 1) ####

# 4.1 Subset data
dd_shan <- long_data %>%
  filter(Metric == "Hill_Shannon") %>%
  drop_na(Value, Plot, Type, same, previous1, same_c, previous1_c) %>%
  mutate(Type = forcats::fct_relevel(Type, "Reserve", "Fragment"))

# 4.2 Model formulas
form_shan_prev  <- Value ~ Type * previous1_c + (1 | Plot)
form_shan_same  <- Value ~ Type * same_c      + (1 | Plot)
form_shan_full  <- Value ~ Type * previous1_c + Type * same_c + (1 | Plot)

# 4.3 Fit models with ML for AIC
m_shan_prev_ml <- lmer(form_shan_prev, data = dd_shan, REML = FALSE)
m_shan_same_ml <- lmer(form_shan_same, data = dd_shan, REML = FALSE)
m_shan_full_ml <- lmer(form_shan_full, data = dd_shan, REML = FALSE)

aic_shan <- tibble(
  model   = c("prev_only", "same_only", "prev+same"),
  formula = c(
    deparse(form_shan_prev),
    deparse(form_shan_same),
    deparse(form_shan_full)
  ),
  AIC     = c(
    AIC(m_shan_prev_ml),
    AIC(m_shan_same_ml),
    AIC(m_shan_full_ml)
  )
) %>%
  arrange(AIC)

print(aic_shan)

# 4.4 Refit models with REML for inference
m_shan_prev_reml <- lmer(form_shan_prev, data = dd_shan, REML = TRUE)
m_shan_same_reml <- lmer(form_shan_same, data = dd_shan, REML = TRUE)
m_shan_full_reml <- lmer(form_shan_full, data = dd_shan, REML = TRUE)
summary(m_shan_full_reml)
# Type III ANOVA
anova_shan_full <- car::Anova(m_shan_full_reml, type = "III")
print(anova_shan_full)


# R2 (Nakagawa)
r2_shan_full <- performance::r2_nakagawa(m_shan_full_reml)
print(r2_shan_full)

# Fixed effects and glance
coef_shan_full <- broom.mixed::tidy(
  m_shan_full_reml,
  effects = "fixed",
  conf.int = TRUE
)
print(coef_shan_full)

glance_shan_full <- broom.mixed::glance(m_shan_full_reml)
print(glance_shan_full)

# 4.5 R2 comparison
r2_mat_shan <- rbind(
  get_r2(m_shan_prev_reml),
  get_r2(m_shan_same_reml),
  get_r2(m_shan_full_reml)
)

r2_table_shan <- tibble(
  model          = c("prev_only", "same_only", "prev+same"),
  formula        = c(
    deparse(form_shan_prev),
    deparse(form_shan_same),
    deparse(form_shan_full)
  ),
  R2_marginal    = r2_mat_shan[, "R2m"],
  R2_conditional = r2_mat_shan[, "R2c"]
)

shan_m <- r2_table_shan$R2_marginal[r2_table_shan$model == "prev+same"]
shan_c <- r2_table_shan$R2_conditional[r2_table_shan$model == "prev+same"]

r2_table_shan <- r2_table_shan %>%
  mutate(
    dR2m_vs_full = R2_marginal    - shan_m,
    dR2c_vs_full = R2_conditional - shan_c
  )

print(r2_table_shan)

# 4.6 Assumption checks — see Section 6 (consolidated diagnostics)

# 4.7 Model-based plots for Hill_Shannon

pred_shan_prev <- ggpredict(
  m_shan_full_reml,
  terms     = c("previous1_c [all]", "Type"),
  condition = list(same_c = 0)
) %>%
  as.data.frame() %>%
  mutate(x_mm = x + mean(dd_shan$previous1, na.rm = TRUE))

pred_shan_same <- ggpredict(
  m_shan_full_reml,
  terms     = c("same_c [all]", "Type"),
  condition = list(previous1_c = 0)
) %>%
  as.data.frame() %>%
  mutate(x_mm = x + mean(dd_shan$same, na.rm = TRUE))

p_shan_prev <- ggplot() +
  geom_point(
    data = dd_shan,
    aes(x = previous1, y = Value, color = Type, shape = Type),
    alpha = 0.3, size = 2
  ) +
  geom_ribbon(
    data = pred_shan_prev,
    aes(x = x_mm, ymin = conf.low, ymax = conf.high, fill = group),
    alpha = 0.25
  ) +
  geom_line(
    data = pred_shan_prev,
    aes(x = x_mm, y = predicted, color = group),
    linewidth = 1.2
  ) +
  scale_color_manual(values = col_vals, guide = "none") +
  scale_fill_manual(values = col_vals, guide = "none") +
  scale_shape_manual(values = shape_vals, guide = "none") +
  labs(
    x = "Previous-year winter precipitation (mm)",
    y = "Hill-Shannon (q = 1)"
  ) +
  theme_classic(base_size = 13)

p_shan_same <- ggplot() +
  geom_point(
    data = dd_shan,
    aes(x = same, y = Value, color = Type, shape = Type),
    alpha = 0.3, size = 2
  ) +
  geom_ribbon(
    data = pred_shan_same,
    aes(x = x_mm, ymin = conf.low, ymax = conf.high, fill = group),
    alpha = 0.25
  ) +
  geom_line(
    data = pred_shan_same,
    aes(x = x_mm, y = predicted, color = group),
    linewidth = 1.2
  ) +
  scale_color_manual(values = col_vals, guide = "none") +
  scale_fill_manual(values = col_vals, guide = "none") +
  scale_shape_manual(values = shape_vals, guide = "none") +
  labs(
    x = "Same-year winter precipitation (mm)",
    y = NULL
  ) +
  theme_classic(base_size = 13)

p_shan_model <- p_shan_prev + p_shan_same + plot_layout(ncol = 2)
print(p_shan_model)

ggsave(file.path(figures_dir, "p_Shan_coverage.svg"), p_shan_model,
       width = 10, height = 4, units = "in", dpi = 600)


#### 5) Hill_Simpson (q = 2) ####

# 5.1 Subset data
dd_simp <- long_data %>%
  filter(Metric == "Hill_Simpson") %>%
  drop_na(Value, Plot, Type, same, previous1, same_c, previous1_c) %>%
  mutate(Type = forcats::fct_relevel(Type, "Reserve", "Fragment"))

# 5.2 Model formulas
form_simp_prev  <- Value ~ Type * previous1_c + (1 | Plot)
form_simp_same  <- Value ~ Type * same_c      + (1 | Plot)
form_simp_full  <- Value ~ Type * previous1_c + Type * same_c + (1 | Plot)

# 5.3 Fit models with ML for AIC
m_simp_prev_ml <- lmer(form_simp_prev, data = dd_simp, REML = FALSE)
m_simp_same_ml <- lmer(form_simp_same, data = dd_simp, REML = FALSE)
m_simp_full_ml <- lmer(form_simp_full, data = dd_simp, REML = FALSE)

aic_simp <- tibble(
  model   = c("prev_only", "same_only", "prev+same"),
  formula = c(
    deparse(form_simp_prev),
    deparse(form_simp_same),
    deparse(form_simp_full)
  ),
  AIC     = c(
    AIC(m_simp_prev_ml),
    AIC(m_simp_same_ml),
    AIC(m_simp_full_ml)
  )
) %>%
  arrange(AIC)

print(aic_simp)

# 5.4 Refit models with REML for inference
m_simp_prev_reml <- lmer(form_simp_prev, data = dd_simp, REML = TRUE)
m_simp_same_reml <- lmer(form_simp_same, data = dd_simp, REML = TRUE)
m_simp_full_reml <- lmer(form_simp_full, data = dd_simp, REML = TRUE)

# Type III ANOVA
anova_simp_full <- car::Anova(m_simp_full_reml, type = "III")
print(anova_simp_full)

# R2 (Nakagawa)
r2_simp_full <- performance::r2_nakagawa(m_simp_full_reml)
print(r2_simp_full)

# Fixed effects and glance
coef_simp_full <- broom.mixed::tidy(
  m_simp_full_reml,
  effects = "fixed",
  conf.int = TRUE
)
print(coef_simp_full)
summary(m_simp_full_reml)
glance_simp_full <- broom.mixed::glance(m_simp_full_reml)
print(glance_simp_full)

# 5.5 R2 comparison
r2_mat_simp <- rbind(
  get_r2(m_simp_prev_reml),
  get_r2(m_simp_same_reml),
  get_r2(m_simp_full_reml)
)

r2_table_simp <- tibble(
  model          = c("prev_only", "same_only", "prev+same"),
  formula        = c(
    deparse(form_simp_prev),
    deparse(form_simp_same),
    deparse(form_simp_full)
  ),
  R2_marginal    = r2_mat_simp[, "R2m"],
  R2_conditional = r2_mat_simp[, "R2c"]
)

simp_m <- r2_table_simp$R2_marginal[r2_table_simp$model == "prev+same"]
simp_c <- r2_table_simp$R2_conditional[r2_table_simp$model == "prev+same"]

r2_table_simp <- r2_table_simp %>%
  mutate(
    dR2m_vs_full = R2_marginal    - simp_m,
    dR2c_vs_full = R2_conditional - simp_c
  )

print(r2_table_simp)

# 5.6 Assumption checks — see Section 6 (consolidated diagnostics)

# 5.7 Model-based plots for Hill_Simpson

pred_simp_prev <- ggpredict(
  m_simp_full_reml,
  terms     = c("previous1_c [all]", "Type"),
  condition = list(same_c = 0)
) %>%
  as.data.frame() %>%
  mutate(x_mm = x + mean(dd_simp$previous1, na.rm = TRUE))

p_simp_prev <- ggplot() +
  geom_point(
    data = dd_simp,
    aes(x = previous1, y = Value, color = Type, shape = Type),
    alpha = 0.3, size = 2
  ) +
  geom_ribbon(
    data = pred_simp_prev,
    aes(x = x_mm, ymin = conf.low, ymax = conf.high, fill = group),
    alpha = 0.25
  ) +
  geom_line(
    data = pred_simp_prev,
    aes(x = x_mm, y = predicted, color = group),
    linewidth = 1.2
  ) +
  scale_color_manual(values = col_vals, guide = "none") +
  scale_fill_manual(values = col_vals, guide = "none") +
  scale_shape_manual(values = shape_vals, guide = "none") +
  labs(
    x = "Previous-year winter precipitation (mm)",
    y = "Hill-Simpson (q = 2)"
  ) +
  theme_classic()

p_simp_same <- ggplot() +
  geom_point(
    data = dd_simp,
    aes(x = same, y = Value, color = Type, shape = Type),
    alpha = 0.3, size = 2
  ) +
  geom_ribbon(
    data = pred_simp_same,
    aes(x = x_mm, ymin = conf.low, ymax = conf.high, fill = group),
    alpha = 0.25
  ) +
  geom_line(
    data = pred_simp_same,
    aes(x = x_mm, y = predicted, color = group),
    linewidth = 1.2
  ) +
  scale_color_manual(values = col_vals, guide = "none") +
  scale_fill_manual(values = col_vals, guide = "none") +
  scale_shape_manual(values = shape_vals, guide = "none") +
  labs(
    x = "Same-year winter precipitation (mm)",
    y = NULL
  ) +
  theme_classic() 

p_simp_model <- p_simp_prev + p_simp_same + plot_layout(ncol = 2)
print(p_simp_model)

ggsave(file.path(figures_dir, "p_simp_coverage.png"), p_simp_model,
       width = 10, height = 4, units = "in", dpi = 300)


# ggsave(file.path(figures_dir, "p_HillSimpson_coverage.pdf"), p_simp_model,
#        width = 10, height = 4, units = "in", dpi = 300)

# 5.8 Export Hill_Simpson results
sheets_simp <- list(
  AIC_table     = aic_simp,
  ANOVA_TypeIII = broom::tidy(anova_simp_full),
  Fixed_Effects = coef_simp_full,
  Model_Glance  = glance_simp_full,
  R2_models     = r2_table_simp
)

writexl::write_xlsx(
  sheets_simp,
  path = file.path(results_dir, "HillSimpson_model_results_COVERAGE.xlsx")
)

# =============================================================================
# SECTION 6 — Model diagnostics
#
# Addresses reviewer concerns about Gaussian assumptions for bounded responses.
# For each full model (richness, Hill-Shannon, Hill-Simpson):
#   (1) Box-Cox test — identifies optimal power transformation
#   (2) Log-transform check — plots raw vs log(Value) distributions
#   (3) DHARMa simulated residuals — tests for misspecification, dispersion,
#       outliers, and residual autocorrelation
#   (4) performance::check_model — visual diagnostics panel
#
# All diagnostic plots saved to figures/diagnostics/
# DHARMa test results saved to results/diagnostics_dharma.xlsx
#
# See supplement for full diagnostic outputs. Models are Gaussian lmer fits;
# diagnostics confirm acceptability of this approximation given that diversity
# values are not concentrated near zero.
# =============================================================================

library(DHARMa)
dir.create(file.path(figures_dir, "diagnostics"), showWarnings = FALSE)

run_diagnostics <- function(model, metric_name, diag_dat) {

  diag_dat <- as.data.frame(diag_dat)  # force plain data.frame

  cat("\n==============================\n")
  cat("Diagnostics:", metric_name, "\n")
  cat("==============================\n")

  # ---- 1) Box-Cox transformation test ----
  y <- diag_dat[["Value"]]
  lambdas <- seq(-2, 2, by = 0.1)
  log_liks <- sapply(lambdas, function(lam) {
    y_trans <- if (abs(lam) < 1e-10) log(y) else (y^lam - 1) / lam
    sum(dnorm(y_trans, mean(y_trans), sd(y_trans), log = TRUE)) +
      (lam - 1) * sum(log(y))
  })
  lambda_opt <- lambdas[which.max(log_liks)]
  cat("Box-Cox optimal lambda:", round(lambda_opt, 3),
      " (log = 0, no transform = 1)\n")

  # ---- 2) Distribution check: raw vs log ----
  png(file.path(figures_dir, "diagnostics",
                paste0(metric_name, "_distribution_check.png")),
      width = 800, height = 400, res = 120)
  par(mfrow = c(1, 2))
  hist(diag_dat[["Value"]], main = paste(metric_name, "- raw"),
       xlab = "Value", col = "steelblue", border = "white")
  hist(log(diag_dat[["Value"]] + 0.001), main = paste(metric_name, "- log"),
       xlab = "log(Value)", col = "coral", border = "white")
  par(mfrow = c(1, 1))
  dev.off()

  # ---- 3) DHARMa simulated residuals ----
  sim_res <- DHARMa::simulateResiduals(model, n = 1000, plot = FALSE)

  png(file.path(figures_dir, "diagnostics",
                paste0(metric_name, "_dharma_residuals.png")),
      width = 900, height = 500, res = 120)
  plot(sim_res, main = metric_name)
  dev.off()

  disp_test    <- DHARMa::testDispersion(sim_res,  plot = FALSE)
  outlier_test <- DHARMa::testOutliers(sim_res,    plot = FALSE)
  unif_test    <- DHARMa::testUniformity(sim_res,  plot = FALSE)

  cat("DHARMa dispersion test p =", round(disp_test$p.value,    4), "\n")
  cat("DHARMa outlier test p =",    round(outlier_test$p.value, 4), "\n")
  cat("DHARMa uniformity test p =", round(unif_test$p.value,    4), "\n")

  # ---- 4) performance::check_model ----
  perf_plot <- performance::check_model(model)
  ggplot2::ggsave(
    file.path(figures_dir, "diagnostics",
              paste0(metric_name, "_check_model.png")),
    plot  = plot(perf_plot),
    width = 12, height = 10, dpi = 150
  )

  tibble::tibble(
    metric           = metric_name,
    boxcox_lambda    = round(lambda_opt,           3),
    dharma_disp_p    = round(disp_test$p.value,    4),
    dharma_outlier_p = round(outlier_test$p.value, 4),
    dharma_uniform_p = round(unif_test$p.value,    4)
  )
}

diag_rich <- run_diagnostics(m_rich_full_reml, "Richness",     dd_rich)
diag_shan <- run_diagnostics(m_shan_full_reml, "Hill_Shannon", dd_shan)
diag_simp <- run_diagnostics(m_simp_full_reml, "Hill_Simpson", dd_simp)

diag_summary <- bind_rows(diag_rich, diag_shan, diag_simp)
print(diag_summary)

writexl::write_xlsx(
  diag_summary,
  path = file.path(results_dir, "diagnostics_dharma.xlsx")
)

cat("\nDiagnostic plots saved to figures/diagnostics/\n")
cat("DHARMa summary saved to results/diagnostics_dharma.xlsx\n")

#### FRAGMENTS ONLY ####

# Helper: safe R2 for lmer fits
get_r2_safe <- function(m) {
  r2 <- suppressWarnings(MuMIn::r.squaredGLMM(m))
  c(R2m = as.numeric(r2[1, "R2m"]), R2c = as.numeric(r2[1, "R2c"]))
}

# Helper: run fragment-only model set for one metric
run_frag_models <- function(metric_name, dat = long_data) {
  
  dd <- dat %>%
    dplyr::filter(Metric == metric_name, Type == "Fragment") %>%
    tidyr::drop_na(Value, Plot, year, same, previous1, same_c, previous1_c)
  
  message("\n==============================")
  message("Fragments-only: ", metric_name)
  message("N rows = ", nrow(dd), " | N plots = ", dplyr::n_distinct(dd$Plot))
  message("==============================")
  
  # Model formulas (no Type term, since fragments only)
  form_prev <- Value ~ previous1_c + (1 | Plot)
  form_same <- Value ~ same_c      + (1 | Plot)
  form_full <- Value ~ previous1_c + same_c + (1 | Plot)
  
  # Fit with ML for AIC comparisons
  m_prev_ml <- lmer(form_prev, data = dd, REML = FALSE)
  m_same_ml <- lmer(form_same, data = dd, REML = FALSE)
  m_full_ml <- lmer(form_full, data = dd, REML = FALSE)
  
  aic_tab <- tibble::tibble(
    Metric  = metric_name,
    model   = c("prev_only", "same_only", "prev+same"),
    formula = c(deparse(form_prev), deparse(form_same), deparse(form_full)),
    AIC     = c(AIC(m_prev_ml), AIC(m_same_ml), AIC(m_full_ml))
  ) %>% dplyr::arrange(AIC)
  
  print(aic_tab)
  
  # Refit with REML for inference (use the full model as the main inference target)
  m_full_reml <- lmer(form_full, data = dd, REML = TRUE)
  
  # Type III tests (consistent with your main pipeline)
  anova_full <- car::Anova(m_full_reml, type = "III")
  print(anova_full)
  
  # R2 (Nakagawa-style via MuMIn, matching your helper)
  r2_full <- get_r2_safe(m_full_reml)
  r2_tab <- tibble::tibble(
    Metric = metric_name,
    model  = "prev+same",
    R2_marginal    = r2_full["R2m"],
    R2_conditional = r2_full["R2c"]
  )
  print(r2_tab)
  
  # Fixed effects table w/ CI
  fe <- broom.mixed::tidy(m_full_reml, effects = "fixed", conf.int = TRUE)
  print(fe)
  
  # Optional: quick plots (prev and same) for fragments-only
  pred_prev <- ggeffects::ggpredict(
    m_full_reml,
    terms     = c("previous1_c [all]"),
    condition = list(same_c = 0)
  ) %>%
    as.data.frame() %>%
    dplyr::mutate(x_mm = x + mean(dd$previous1, na.rm = TRUE))
  
  pred_same <- ggeffects::ggpredict(
    m_full_reml,
    terms     = c("same_c [all]"),
    condition = list(previous1_c = 0)
  ) %>%
    as.data.frame() %>%
    dplyr::mutate(x_mm = x + mean(dd$same, na.rm = TRUE))
  
  p_prev <- ggplot2::ggplot() +
    ggplot2::geom_point(
      data = dd,
      ggplot2::aes(x = previous1, y = Value),
      alpha = 0.35, size = 2
    ) +
    ggplot2::geom_ribbon(
      data = pred_prev,
      ggplot2::aes(x = x_mm, ymin = conf.low, ymax = conf.high),
      alpha = 0.25
    ) +
    ggplot2::geom_line(
      data = pred_prev,
      ggplot2::aes(x = x_mm, y = predicted),
      linewidth = 1.2
    ) +
    ggplot2::theme_classic() +
    ggplot2::labs(x = "Previous-year winter precipitation (mm)",
                  y = paste0(metric_name, " (fragments only)"))
  
  p_same <- ggplot2::ggplot() +
    ggplot2::geom_point(
      data = dd,
      ggplot2::aes(x = same, y = Value),
      alpha = 0.35, size = 2
    ) +
    ggplot2::geom_ribbon(
      data = pred_same,
      ggplot2::aes(x = x_mm, ymin = conf.low, ymax = conf.high),
      alpha = 0.25
    ) +
    ggplot2::geom_line(
      data = pred_same,
      ggplot2::aes(x = x_mm, y = predicted),
      linewidth = 1.2
    ) +
    ggplot2::theme_classic() +
    ggplot2::labs(x = "Same-year winter precipitation (mm)",
                  y = NULL)
  
  p_both <- p_prev + p_same + patchwork::plot_layout(ncol = 2)
  print(p_both)
  
  # Save plots (filenames safe)
  safe_metric <- gsub("[^A-Za-z0-9_]+", "_", metric_name)
  ggplot2::ggsave(
    filename = paste0("fragOnly_", safe_metric, "_precip.png"),
    plot = p_both, width = 10, height = 4, units = "in", dpi = 300
  )
  
  list(
    data      = dd,
    aic       = aic_tab,
    anova     = broom::tidy(anova_full),
    fixed     = fe,
    r2        = r2_tab,
    model_reml = m_full_reml
  )
}

# Run for q0–q2 metrics
frag_results <- list(
  Richness      = run_frag_models("Richness"),
  Hill_Shannon  = run_frag_models("Hill_Shannon"),
  Hill_Simpson  = run_frag_models("Hill_Simpson")
)

# Combine + export to one Excel workbook
aic_all   <- dplyr::bind_rows(lapply(frag_results, `[[`, "aic"))
anova_all <- dplyr::bind_rows(lapply(frag_results, `[[`, "anova"), .id = "Metric_list")
fixed_all <- dplyr::bind_rows(lapply(frag_results, `[[`, "fixed"), .id = "Metric_list")
r2_all    <- dplyr::bind_rows(lapply(frag_results, `[[`, "r2"))

writexl::write_xlsx(
  list(
    AIC_tables     = aic_all,
    ANOVA_TypeIII  = anova_all,
    Fixed_Effects  = fixed_all,
    R2_full_models = r2_all
  ),
  path = file.path(results_dir, "FragmentsOnly_precip_tests_q0_q2_COVERAGE.xlsx")
)

#### RESERVES ONLY ####

# Helper: safe R2 for lmer fits
get_r2_safe <- function(m) {
  r2 <- suppressWarnings(MuMIn::r.squaredGLMM(m))
  c(R2m = as.numeric(r2[1, "R2m"]), R2c = as.numeric(r2[1, "R2c"]))
}

# Helper: run reserve-only model set for one metric
run_reserve_models <- function(metric_name, dat = long_data) {
  
  dd <- dat %>%
    dplyr::filter(Metric == metric_name, Type == "Fragment") %>%   # <-- RESERVES
    tidyr::drop_na(Value, Plot, year, same, previous1, same_c, previous1_c)
  
  message("\n==============================")
  message("Reserves-only: ", metric_name)
  message("N rows = ", nrow(dd), " | N plots = ", dplyr::n_distinct(dd$Plot))
  message("==============================")
  
  # Model formulas (no Type term)
  form_prev <- Value ~ previous1_c + (1 | Plot)
  form_same <- Value ~ same_c      + (1 | Plot)
  form_full <- Value ~ previous1_c + same_c + (1 | Plot)
  
  # ML fits for AIC
  m_prev_ml <- lmer(form_prev, data = dd, REML = FALSE)
  m_same_ml <- lmer(form_same, data = dd, REML = FALSE)
  m_full_ml <- lmer(form_full, data = dd, REML = FALSE)
  
  aic_tab <- tibble::tibble(
    Metric  = metric_name,
    model   = c("prev_only", "same_only", "prev+same"),
    formula = c(deparse(form_prev), deparse(form_same), deparse(form_full)),
    AIC     = c(AIC(m_prev_ml), AIC(m_same_ml), AIC(m_full_ml))
  ) %>% dplyr::arrange(AIC)
  
  print(aic_tab)
  
  # REML for inference
  m_full_reml <- lmer(form_full, data = dd, REML = TRUE)
  anova_full <- car::Anova(m_full_reml, type = "III")
  print(anova_full)
  
  # R2
  r2_full <- get_r2_safe(m_full_reml)
  r2_tab <- tibble::tibble(
    Metric = metric_name,
    model  = "prev+same",
    R2_marginal    = r2_full["R2m"],
    R2_conditional = r2_full["R2c"]
  )
  print(r2_tab)
  
  # Fixed effects
  fe <- broom.mixed::tidy(m_full_reml, effects = "fixed", conf.int = TRUE)
  print(fe)
  
  # Predictions (no ggpredict in final figs — same structure you used)
  pred_prev <- ggeffects::ggpredict(
    m_full_reml,
    terms = c("previous1_c [all]"),
    condition = list(same_c = 0)
  ) %>%
    as.data.frame() %>%
    dplyr::mutate(x_mm = x + mean(dd$previous1, na.rm = TRUE))
  
  pred_same <- ggeffects::ggpredict(
    m_full_reml,
    terms = c("same_c [all]"),
    condition = list(previous1_c = 0)
  ) %>%
    as.data.frame() %>%
    dplyr::mutate(x_mm = x + mean(dd$same, na.rm = TRUE))
  
  # ---- PLOTS (GREEN LINES) ----
  
  p_prev <- ggplot2::ggplot() +
    ggplot2::geom_point(
      data = dd,
      ggplot2::aes(x = previous1, y = Value),
      color = "gray40", alpha = 0.35, size = 2
    ) +
    ggplot2::geom_ribbon(
      data = pred_prev,
      ggplot2::aes(x = x_mm, ymin = conf.low, ymax = conf.high),
      fill = "darkgreen", alpha = 0.25
    ) +
    ggplot2::geom_line(
      data = pred_prev,
      ggplot2::aes(x = x_mm, y = predicted),
      color = "darkgreen", linewidth = 1.2
    ) +
    ggplot2::theme_classic(base_size = 13) +
    ggplot2::labs(
      x = "Previous-year winter precipitation (mm)",
      y = paste0(metric_name, " (reserves only)")
    )
  
  p_same <- ggplot2::ggplot() +
    ggplot2::geom_point(
      data = dd,
      ggplot2::aes(x = same, y = Value),
      color = "gray40", alpha = 0.35, size = 2
    ) +
    ggplot2::geom_ribbon(
      data = pred_same,
      ggplot2::aes(x = x_mm, ymin = conf.low, ymax = conf.high),
      fill = "darkgreen", alpha = 0.25
    ) +
    ggplot2::geom_line(
      data = pred_same,
      ggplot2::aes(x = x_mm, y = predicted),
      color = "darkgreen", linewidth = 1.2
    ) +
    ggplot2::theme_classic(base_size = 13) +
    ggplot2::labs(
      x = "Same-year winter precipitation (mm)",
      y = NULL
    )
  
  p_both <- p_prev + p_same + patchwork::plot_layout(ncol = 2)
  print(p_both)
  
  # Save
  safe_metric <- gsub("[^A-Za-z0-9_]+", "_", metric_name)
  ggplot2::ggsave(
    filename = paste0("ReserveOnly_", safe_metric, "_precip.png"),
    plot = p_both,
    width = 10, height = 4, units = "in", dpi = 300
  )
  
  list(
    data        = dd,
    aic         = aic_tab,
    anova       = broom::tidy(anova_full),
    fixed       = fe,
    r2          = r2_tab,
    model_reml  = m_full_reml
  )
}

# Run for q0–q2 metrics
reserve_results <- list(
  Richness     = run_reserve_models("Richness"),
  Hill_Shannon = run_reserve_models("Hill_Shannon"),
  Hill_Simpson = run_reserve_models("Hill_Simpson")
)

reserve_results$Richness$anova
reserve_results$Hill_Shannon$anova
reserve_results$Hill_Simpson$anova


# 6-panel per Type (Fragment + Reserve), with:
# - Left column = WP_{y0-1} (mm)
# - Right column = WP_{y0} (mm)
# - ONE bottom label row (not repeated)
# - EACH row labeled with the metric name (shown once per row, on the left panel)

library(dplyr)
library(tidyr)
library(lme4)
library(ggeffects)
library(ggplot2)
library(patchwork)

type_cols <- c(Fragment = "gray52", Reserve = "springgreen4")

metric_titles <- c(
  Richness     = "Richness (q = 0)",
  Hill_Shannon = "Hill–Shannon (q = 1)",
  Hill_Simpson = "Hill–Simpson (q = 2)"
)

one_panel <- function(metric_name, type_name, which = c("prev", "same"),
                      show_row_title = FALSE, dat = long_data) {
  which <- match.arg(which)
  
  dd <- dat %>%
    filter(Metric == metric_name, Type == type_name) %>%
    drop_na(Value, Plot, previous1, same, previous1_c, same_c)
  
  m <- lmer(Value ~ previous1_c + same_c + (1 | Plot), data = dd, REML = TRUE)
  
  if (which == "prev") {
    pred <- ggpredict(m, terms = "previous1_c [all]", condition = list(same_c = 0)) %>%
      as.data.frame() %>%
      mutate(x_mm = x + mean(dd$previous1, na.rm = TRUE))
    pts <- dd %>% transmute(x = previous1, Value = Value)
  } else {
    pred <- ggpredict(m, terms = "same_c [all]", condition = list(previous1_c = 0)) %>%
      as.data.frame() %>%
      mutate(x_mm = x + mean(dd$same, na.rm = TRUE))
    pts <- dd %>% transmute(x = same, Value = Value)
  }
  
  ggplot() +
    geom_point(data = pts, aes(x = x, y = Value),
               color = "gray40", alpha = 0.35, size = 1.8) +
    geom_ribbon(data = pred, aes(x = x_mm, ymin = conf.low, ymax = conf.high),
                fill = type_cols[[type_name]], alpha = 0.20) +
    geom_line(data = pred, aes(x = x_mm, y = predicted),
              color = type_cols[[type_name]], linewidth = 1.1) +
    theme_classic(base_size = 13) +
    theme(
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      plot.title = element_text(face = "bold", hjust = 0)
    ) +
    labs(title = if (show_row_title) metric_titles[[metric_name]] else NULL)
}

make_6panel_one_type <- function(type_name, dat = long_data) {
  
  # For each row: left (prev) shows the metric title; right (same) has no title.
  panels <- list(
    one_panel("Richness",     type_name, "prev", show_row_title = TRUE,  dat = dat),
    one_panel("Richness",     type_name, "same", show_row_title = FALSE, dat = dat),
    
    one_panel("Hill_Shannon", type_name, "prev", show_row_title = TRUE,  dat = dat),
    one_panel("Hill_Shannon", type_name, "same", show_row_title = FALSE, dat = dat),
    
    one_panel("Hill_Simpson", type_name, "prev", show_row_title = TRUE,  dat = dat),
    one_panel("Hill_Simpson", type_name, "same", show_row_title = FALSE, dat = dat)
  )
  
  p_main <- wrap_plots(panels, ncol = 2)
  
  # single bottom label row
  p_labels <- ggplot() +
    theme_void() +
    annotate("text", x = 0.25, y = 0.5,
             label = "WP[y[0-1]]~'(mm)'", parse = TRUE, size = 5) +
    annotate("text", x = 0.75, y = 0.5,
             label = "WP[y[0]]~'(mm)'", parse = TRUE, size = 5) +
    xlim(0, 1) + ylim(0, 1)
  
  # add Type header as a figure-level title
  (p_main / p_labels + plot_layout(heights = c(20, 1))) +
    plot_annotation(title = paste0(type_name, "s")) &
    theme(plot.title = element_text(face = "bold", size = 16, hjust = 0))
}

# ---- build both figures ----
p_frag <- make_6panel_one_type("Fragment", long_data)
p_res  <- make_6panel_one_type("Reserve",  long_data)

p_frag
p_res

ggsave(file.path(figures_dir, "Fig_Fragment_6panel_WP.png"), p_frag, width = 10, height = 12, dpi = 300)
ggsave(file.path(figures_dir, "Fig_Reserve_6panel_WP.png"),  p_res,  width = 10, height = 12, dpi = 300)
ggsave(file.path(figures_dir, "Fig_Fragment_6panel_WP.svg"), p_frag, width = 10, height = 12)
ggsave(file.path(figures_dir, "Fig_Reserve_6panel_WP.svg"),  p_res,  width = 10, height = 12)
