## =============================================================================
## R-05_bee_diversity.R
##
## Purpose : Test Prediction 2 — bee diversity increases with winter
##           precipitation. Coverage-standardized Hill numbers (q=0,1,2)
##           via iNEXT::estimateD() at the shared coverage target from R-01.
##           Mixed-effects models with WPy0, WPy0-1, site type, and
##           interactions. AIC model comparison; marginal R² via MuMIn.
##           Main analysis (coverage-standardized; not sensitivity rarefaction).
##
## Inputs  : data/cleaned/df_analysis.csv       — filtered occurrence records
##                                                 (generated by R-01)
##           data/cleaned/target_coverage.rds   — shared coverage target scalar
##                                                 (generated by R-01)
##           data/cleaned/precipyrs.csv         — annual winter totals + lags
##                                                 (generated by R-02)
##
## Outputs : figures/Fig_diversity_coverage_*.svg
##           results/All_model_results.xlsx      — consolidated single workbook
##
## Author  : Jess Mullins
## Date    : 6-April-2026
## =============================================================================

#### =========================================
#### Bee diversity: coverage-standardized Hill numbers
#### =========================================

#### 0) Packages ####
suppressPackageStartupMessages({
  library(tidyverse)
  library(vegan)
  library(iNEXT)
  library(lme4)
  library(lmerTest)
  library(car)
  library(performance)
  library(forcats)
  library(patchwork)
  library(ggeffects)
  library(broom)
  library(broom.mixed)
  library(writexl)
  library(MuMIn)
  library(DHARMa)
  library(MASS)
})

## File paths
figures_dir <- "figures"
results_dir <- "results"
cleaned_dir <- "data/cleaned"
raw_dir     <- "data/raw"

#### 1) Load data ####

df_analysis <- read.csv(file.path(cleaned_dir, "df_analysis.csv"))

target_cov <- readRDS(file.path(cleaned_dir, "target_coverage.rds"))
cat("Loaded target coverage from R-01:", round(target_cov, 4), "\n")

precipitation_yearly <- read.csv(file.path(cleaned_dir, "precipyrs.csv")) %>%
  drop_na()

indicators <- readRDS(file.path(cleaned_dir, "indicator_species.rds"))

# Filter out:
df_analysis %>% filter(!scientificName %in% indicators)
precipitation_yearly$year <- as.factor(precipitation_yearly$year)
mean_same  <- mean(precipitation_yearly$same,      na.rm = TRUE)
mean_prev  <- mean(precipitation_yearly$previous1, na.rm = TRUE)
mean_prev2 <- mean(precipitation_yearly$previous2, na.rm = TRUE)

#### 2) Coverage-standardized Hill numbers (q = 0,1,2) ####

allbees <- df_analysis %>%
  rename(Plot = fieldNumber) %>%
  mutate(
    year      = as.factor(year),
    Count     = as.numeric(Count),
    plot_year = paste(Plot, year, sep = "_")
  ) 
# %>% filter(!scientificName %in% indicators) # unhash this to run without indicator spp

comm <- allbees %>%
  group_by(plot_year, Plot, year, Type, scientificName) %>%
  summarise(n = sum(Count), .groups = "drop") %>%
  pivot_wider(names_from = scientificName, values_from = n, values_fill = 0)

meta <- comm %>%
  dplyr::select(plot_year, Plot, year, Type)

species_cols <- setdiff(names(comm), c("plot_year","Plot","year","Type"))

abund_list <- apply(
  comm[, species_cols, drop = FALSE],
  1,
  function(z) {
    z <- as.numeric(z)
    z[z > 0]
  }
)
names(abund_list) <- comm$plot_year

# rarefy
est <- iNEXT::estimateD(
  abund_list,
  q        = c(0, 1, 2),
  datatype = "abundance",
  base     = "coverage",
  level    = target_cov # lowest coverage observed
) %>%
  as_tibble()

long_cov <- est %>%
  transmute(
    plot_year = Assemblage,
    Order.q,
    SC,
    qD
  ) %>%
  left_join(meta, by = "plot_year") %>%
  mutate(
    Metric = dplyr::recode(
      Order.q,
      `0` = "Richness",
      `1` = "Hill_Shannon",
      `2` = "Hill_Simpson"
    ),
    Method = paste0("Coverage (common SC = ", round(SC[1], 2), ")")
  ) %>%
  dplyr::select(
    Plot, Type, year, plot_year, Metric,
    Value = qD,
    common_coverage = SC, Method
  )

long_cov <- long_cov %>%
  left_join(
    precipitation_yearly %>%
      dplyr::select(year, same, previous1, previous2),
    by = "year"
  ) %>%
  mutate(
    same_c      = same      - mean_same,
    previous1_c = previous1 - mean_prev,
    previous2_c = previous2 - mean_prev2
  )

long_data <- long_cov

col_vals   <- c(Reserve = "#2C7C4D", Fragment = "#BDBDBD")
shape_vals <- c(Reserve = 17,        Fragment = 16)

get_r2 <- function(m) {
  r2 <- suppressWarnings(MuMIn::r.squaredGLMM(m))
  c(R2m = as.numeric(r2[1, "R2m"]), R2c = as.numeric(r2[1, "R2c"]))
}

# Helper: compute the true back-transform constant for a centered variable.
# Works correctly regardless of whether centering happened on the full dataset
# or a subset (e.g. after filtering/dropping NAs).
centering_offset <- function(raw, centered) {
  mean(raw, na.rm = TRUE) - mean(centered, na.rm = TRUE)
}

#### 3) Richness (q = 0) ####

dd_rich <- long_data %>%
  filter(Metric == "Richness") %>%
  drop_na(Value, Plot, Type, same, previous1, same_c, previous1_c) %>%
  mutate(Type = forcats::fct_relevel(Type, "Reserve", "Fragment"))

form_rich_prev  <- Value ~ Type * previous1_c + (1 | Plot)
form_rich_same  <- Value ~ Type * same_c      + (1 | Plot)
form_rich_full  <- Value ~ Type * previous1_c + Type * same_c + (1 | Plot)
form_rich_null  <- Value ~ (1 | Plot)   # null model: random effect only, no fixed effects

m_rich_prev_ml <- lmer(form_rich_prev, data = dd_rich, REML = FALSE)
m_rich_same_ml <- lmer(form_rich_same, data = dd_rich, REML = FALSE)
m_rich_full_ml <- lmer(form_rich_full, data = dd_rich, REML = FALSE)
m_rich_null_ml <- lmer(form_rich_null, data = dd_rich, REML = FALSE)

aic_rich <- tibble(
  model   = c("prev_only", "same_only", "prev+same", "null"),
  formula = c(deparse(form_rich_prev), deparse(form_rich_same),
              deparse(form_rich_full), deparse(form_rich_null)),
  AICc    = c(MuMIn::AICc(m_rich_prev_ml), MuMIn::AICc(m_rich_same_ml),
              MuMIn::AICc(m_rich_full_ml), MuMIn::AICc(m_rich_null_ml))
) %>% arrange(AICc)
print(aic_rich)

m_rich_prev_reml <- lmer(form_rich_prev, data = dd_rich, REML = TRUE)
m_rich_same_reml <- lmer(form_rich_same, data = dd_rich, REML = TRUE)
m_rich_full_reml <- lmer(form_rich_full, data = dd_rich, REML = TRUE)

anova_rich_full <- car::Anova(m_rich_full_reml, type = "III")
print(anova_rich_full)

# --- Reviewer-requested addition: year as a random effect --------------------
# Sites sampled in the same year share the same WPy0/WPy0-1 value (these are
# year-level, not site-level, predictors), so treating site-years as fully
# independent overstates the effective sample size for the precipitation
# effect. Adding (1 | year) forces the precipitation effect to be estimated
# from genuine between-year variation (~7 years), which is the statistically
# honest approach -- expect wider CIs / possibly weaker significance for
# WPy0 and WPy0-1 specifically, since that is the correction working as
# intended, not a bug.
form_rich_full_year <- Value ~ Type * previous1_c + Type * same_c + (1 | Plot) + (1 | year)
m_rich_full_year_reml <- lmer(form_rich_full_year, data = dd_rich, REML = TRUE)
cat("\nSingular fit (year RE model)?", lme4::isSingular(m_rich_full_year_reml), "\n")

anova_rich_full_year <- car::Anova(m_rich_full_year_reml, type = "III")
print(anova_rich_full_year)

compare_anova <- function(anova_no_year, anova_with_year, metric_name) {
  a1 <- as.data.frame(anova_no_year)   %>% tibble::rownames_to_column("term")
  a2 <- as.data.frame(anova_with_year) %>% tibble::rownames_to_column("term")
  full_join(
    a1 %>% dplyr::select(term, Chisq_no_year = Chisq, P_no_year = `Pr(>Chisq)`),
    a2 %>% dplyr::select(term, Chisq_with_year = Chisq, P_with_year = `Pr(>Chisq)`),
    by = "term"
  ) %>%
    mutate(Metric = metric_name, .before = 1)
}

compare_rich <- compare_anova(anova_rich_full, anova_rich_full_year, "Richness")
print(compare_rich)

# --- AICc/R2 comparison for the +year models (mirrors the no-year AICc/R2
# comparison earlier in this section, so both are permanently reproducible
# from this script rather than a one-off scratch calculation) ---------------
m_rich_prev_year_ml <- lmer(form_rich_prev, data = dd_rich, REML = FALSE) %>%
  update(. ~ . + (1 | year))
m_rich_same_year_ml <- lmer(form_rich_same, data = dd_rich, REML = FALSE) %>%
  update(. ~ . + (1 | year))
m_rich_full_year_ml <- update(m_rich_full_year_reml, REML = FALSE)
m_rich_null_year_ml <- lmer(Value ~ (1 | Plot) + (1 | year), data = dd_rich, REML = FALSE)

aic_rich_year <- tibble(
  model = c("prev_only", "same_only", "prev+same", "null"),
  AICc  = c(MuMIn::AICc(m_rich_prev_year_ml), MuMIn::AICc(m_rich_same_year_ml),
            MuMIn::AICc(m_rich_full_year_ml), MuMIn::AICc(m_rich_null_year_ml))
) %>% arrange(AICc)
cat("\n--- Richness AICc, +year models ---\n")
print(aic_rich_year)

m_rich_prev_year_reml <- update(m_rich_prev_year_ml, REML = TRUE)
m_rich_same_year_reml <- update(m_rich_same_year_ml, REML = TRUE)

r2_rich_full_year_check <- performance::r2_nakagawa(m_rich_full_year_reml)
r2_rich_prev_year <- performance::r2_nakagawa(m_rich_prev_year_reml)
r2_rich_same_year <- performance::r2_nakagawa(m_rich_same_year_reml)
cat("Richness +year -- Full R2m:", r2_rich_full_year_check$R2_marginal,
    " Prev-only R2m:", r2_rich_prev_year$R2_marginal,
    " Same-only R2m:", r2_rich_same_year$R2_marginal, "\n")

r2_rich_full_year <- performance::r2_nakagawa(m_rich_full_year_reml)

r2_rich_full <- performance::r2_nakagawa(m_rich_full_reml)
print(r2_rich_full)
summary(m_rich_full_reml)

coef_rich_full <- broom.mixed::tidy(m_rich_full_reml, effects = "fixed", conf.int = TRUE)
print(coef_rich_full)

glance_rich_full <- broom.mixed::glance(m_rich_full_reml)
print(glance_rich_full)

r2_mat_rich <- rbind(get_r2(m_rich_prev_reml), get_r2(m_rich_same_reml), get_r2(m_rich_full_reml))
r2_table_rich <- tibble(
  model          = c("prev_only", "same_only", "prev+same"),
  formula        = c(deparse(form_rich_prev), deparse(form_rich_same), deparse(form_rich_full)),
  R2_marginal    = r2_mat_rich[, "R2m"],
  R2_conditional = r2_mat_rich[, "R2c"]
)
rich_m <- r2_table_rich$R2_marginal[r2_table_rich$model == "prev+same"]
rich_c <- r2_table_rich$R2_conditional[r2_table_rich$model == "prev+same"]
r2_table_rich <- r2_table_rich %>%
  mutate(dR2m_vs_full = R2_marginal - rich_m, dR2c_vs_full = R2_conditional - rich_c)
print(r2_table_rich)

# 3.7 Model-based plots for Richness
rich_prev_offset <- centering_offset(dd_rich$previous1, dd_rich$previous1_c)
rich_same_offset <- centering_offset(dd_rich$same,      dd_rich$same_c)

prev_seq_rich <- seq(min(dd_rich$previous1_c, na.rm = TRUE),
                     max(dd_rich$previous1_c, na.rm = TRUE), length.out = 200)
same_seq_rich <- seq(min(dd_rich$same_c,      na.rm = TRUE),
                     max(dd_rich$same_c,      na.rm = TRUE), length.out = 200)

pred_rich_prev <- ggpredict(
  m_rich_full_reml,
  terms     = c("previous1_c [prev_seq_rich]", "Type"),
  condition = list(same_c = 0)
) %>% as.data.frame() %>% mutate(x_mm = x + rich_prev_offset)

pred_rich_same <- ggpredict(
  m_rich_full_reml,
  terms     = c("same_c [same_seq_rich]", "Type"),
  condition = list(previous1_c = 0)
) %>% as.data.frame() %>% mutate(x_mm = x + rich_same_offset)

p_rich_prev <- ggplot() +
  geom_point(data = dd_rich, aes(x = previous1, y = Value, color = Type, shape = Type),
             alpha = 0.35, size = 2) +
  geom_ribbon(data = pred_rich_prev,
              aes(x = x_mm, ymin = conf.low, ymax = conf.high, fill = group),
              alpha = 0.25, show.legend = FALSE) +
  geom_line(data = pred_rich_prev,
            aes(x = x_mm, y = predicted, color = group),
            linewidth = 1.2, show.legend = FALSE) +
  scale_color_manual(values = col_vals, name = "Site type") +
  scale_shape_manual(values = shape_vals, name = "Site type") +
  scale_fill_manual(values = col_vals, guide = "none") +
  labs(x = NULL, y = "Richness (q = 0)") +
  theme_classic(base_size = 13) +
  theme(legend.position = "none")

p_rich_same <- ggplot() +
  geom_point(data = dd_rich, aes(x = same, y = Value, color = Type, shape = Type),
             alpha = 0.35, size = 2) +
  geom_ribbon(data = pred_rich_same,
              aes(x = x_mm, ymin = conf.low, ymax = conf.high, fill = group),
              alpha = 0.25, show.legend = FALSE) +
  geom_line(data = pred_rich_same,
            aes(x = x_mm, y = predicted, color = group),
            linewidth = 1.2, show.legend = FALSE) +
  scale_color_manual(values = col_vals, name = "Site type") +
  scale_shape_manual(values = shape_vals, name = "Site type") +
  scale_fill_manual(values = col_vals, guide = "none") +
  labs(x = NULL, y = NULL) +
  theme_classic(base_size = 13) +
  theme(legend.position = "none")

p_rich_model <- p_rich_prev + p_rich_same + plot_layout(ncol = 2)
print(p_rich_model)
ggsave(file.path(figures_dir, "p_Richness_coverage2.svg"), p_rich_model,
       width = 10, height = 4, units = "in", dpi = 600)


#### 4) Hill_Shannon (q = 1) ####

dd_shan <- long_data %>%
  filter(Metric == "Hill_Shannon") %>%
  drop_na(Value, Plot, Type, same, previous1, same_c, previous1_c) %>%
  mutate(Type = forcats::fct_relevel(Type, "Reserve", "Fragment"))

form_shan_prev  <- Value ~ Type * previous1_c + (1 | Plot)
form_shan_same  <- Value ~ Type * same_c      + (1 | Plot)
form_shan_full  <- Value ~ Type * previous1_c + Type * same_c + (1 | Plot)
form_shan_null  <- Value ~ (1 | Plot)

m_shan_prev_ml <- lmer(form_shan_prev, data = dd_shan, REML = FALSE)
m_shan_same_ml <- lmer(form_shan_same, data = dd_shan, REML = FALSE)
m_shan_full_ml <- lmer(form_shan_full, data = dd_shan, REML = FALSE)
m_shan_null_ml <- lmer(form_shan_null, data = dd_shan, REML = FALSE)

aic_shan <- tibble(
  model   = c("prev_only", "same_only", "prev+same", "null"),
  formula = c(deparse(form_shan_prev), deparse(form_shan_same),
              deparse(form_shan_full), deparse(form_shan_null)),
  AICc    = c(MuMIn::AICc(m_shan_prev_ml), MuMIn::AICc(m_shan_same_ml),
              MuMIn::AICc(m_shan_full_ml), MuMIn::AICc(m_shan_null_ml))
) %>% arrange(AICc)
print(aic_shan)

m_shan_prev_reml <- lmer(form_shan_prev, data = dd_shan, REML = TRUE)
m_shan_same_reml <- lmer(form_shan_same, data = dd_shan, REML = TRUE)
m_shan_full_reml <- lmer(form_shan_full, data = dd_shan, REML = TRUE)
summary(m_shan_full_reml)

anova_shan_full <- car::Anova(m_shan_full_reml, type = "III")
print(anova_shan_full)

# --- year as a random effect (see Richness section above for rationale) ----
form_shan_full_year <- Value ~ Type * previous1_c + Type * same_c + (1 | Plot) + (1 | year)
m_shan_full_year_reml <- lmer(form_shan_full_year, data = dd_shan, REML = TRUE)
cat("\nSingular fit (year RE model)?", lme4::isSingular(m_shan_full_year_reml), "\n")

anova_shan_full_year <- car::Anova(m_shan_full_year_reml, type = "III")
print(anova_shan_full_year)

compare_shan <- compare_anova(anova_shan_full, anova_shan_full_year, "Hill_Shannon")
print(compare_shan)

# --- AICc/R2 comparison for the +year models --------------------------------
m_shan_prev_year_ml <- lmer(form_shan_prev, data = dd_shan, REML = FALSE) %>%
  update(. ~ . + (1 | year))
m_shan_same_year_ml <- lmer(form_shan_same, data = dd_shan, REML = FALSE) %>%
  update(. ~ . + (1 | year))
m_shan_full_year_ml <- update(m_shan_full_year_reml, REML = FALSE)
m_shan_null_year_ml <- lmer(Value ~ (1 | Plot) + (1 | year), data = dd_shan, REML = FALSE)

aic_shan_year <- tibble(
  model = c("prev_only", "same_only", "prev+same", "null"),
  AICc  = c(MuMIn::AICc(m_shan_prev_year_ml), MuMIn::AICc(m_shan_same_year_ml),
            MuMIn::AICc(m_shan_full_year_ml), MuMIn::AICc(m_shan_null_year_ml))
) %>% arrange(AICc)
cat("\n--- Hill-Shannon AICc, +year models ---\n")
print(aic_shan_year)

m_shan_prev_year_reml <- update(m_shan_prev_year_ml, REML = TRUE)
m_shan_same_year_reml <- update(m_shan_same_year_ml, REML = TRUE)

r2_shan_full_year_check <- performance::r2_nakagawa(m_shan_full_year_reml)
r2_shan_prev_year <- performance::r2_nakagawa(m_shan_prev_year_reml)
r2_shan_same_year <- performance::r2_nakagawa(m_shan_same_year_reml)
cat("Shannon +year -- Full R2m:", r2_shan_full_year_check$R2_marginal,
    " Prev-only R2m:", r2_shan_prev_year$R2_marginal,
    " Same-only R2m:", r2_shan_same_year$R2_marginal, "\n")

r2_shan_full_year <- performance::r2_nakagawa(m_shan_full_year_reml)

r2_shan_full <- performance::r2_nakagawa(m_shan_full_reml)
print(r2_shan_full)

coef_shan_full <- broom.mixed::tidy(m_shan_full_reml, effects = "fixed", conf.int = TRUE)
print(coef_shan_full)

glance_shan_full <- broom.mixed::glance(m_shan_full_reml)
print(glance_shan_full)

r2_mat_shan <- rbind(get_r2(m_shan_prev_reml), get_r2(m_shan_same_reml), get_r2(m_shan_full_reml))
r2_table_shan <- tibble(
  model          = c("prev_only", "same_only", "prev+same"),
  formula        = c(deparse(form_shan_prev), deparse(form_shan_same), deparse(form_shan_full)),
  R2_marginal    = r2_mat_shan[, "R2m"],
  R2_conditional = r2_mat_shan[, "R2c"]
)
shan_m <- r2_table_shan$R2_marginal[r2_table_shan$model == "prev+same"]
shan_c <- r2_table_shan$R2_conditional[r2_table_shan$model == "prev+same"]
r2_table_shan <- r2_table_shan %>%
  mutate(dR2m_vs_full = R2_marginal - shan_m, dR2c_vs_full = R2_conditional - shan_c)
print(r2_table_shan)

# 4.7 Model-based plots for Hill_Shannon
shan_prev_offset <- centering_offset(dd_shan$previous1, dd_shan$previous1_c)
shan_same_offset <- centering_offset(dd_shan$same,      dd_shan$same_c)

prev_seq_shan <- seq(min(dd_shan$previous1_c, na.rm = TRUE),
                     max(dd_shan$previous1_c, na.rm = TRUE), length.out = 200)
same_seq_shan <- seq(min(dd_shan$same_c,      na.rm = TRUE),
                     max(dd_shan$same_c,      na.rm = TRUE), length.out = 200)

pred_shan_prev <- ggpredict(
  m_shan_full_reml,
  terms     = c("previous1_c [prev_seq_shan]", "Type"),
  condition = list(same_c = 0)
) %>% as.data.frame() %>% mutate(x_mm = x + shan_prev_offset)

pred_shan_same <- ggpredict(
  m_shan_full_reml,
  terms     = c("same_c [same_seq_shan]", "Type"),
  condition = list(previous1_c = 0)
) %>% as.data.frame() %>% mutate(x_mm = x + shan_same_offset)

p_shan_prev <- ggplot() +
  geom_point(data = dd_shan, aes(x = previous1, y = Value, color = Type, shape = Type),
             alpha = 0.3, size = 2) +
  geom_ribbon(data = pred_shan_prev,
              aes(x = x_mm, ymin = conf.low, ymax = conf.high, fill = group), alpha = 0.25) +
  geom_line(data = pred_shan_prev,
            aes(x = x_mm, y = predicted, color = group), linewidth = 1.2) +
  scale_color_manual(values = col_vals, guide = "none") +
  scale_fill_manual(values = col_vals, guide = "none") +
  scale_shape_manual(values = shape_vals, guide = "none") +
  labs(x = "Previous-year winter precipitation (mm)", y = "Hill-Shannon (q = 1)") +
  theme_classic(base_size = 13)

p_shan_same <- ggplot() +
  geom_point(data = dd_shan, aes(x = same, y = Value, color = Type, shape = Type),
             alpha = 0.3, size = 2) +
  geom_ribbon(data = pred_shan_same,
              aes(x = x_mm, ymin = conf.low, ymax = conf.high, fill = group), alpha = 0.25) +
  geom_line(data = pred_shan_same,
            aes(x = x_mm, y = predicted, color = group), linewidth = 1.2) +
  scale_color_manual(values = col_vals, guide = "none") +
  scale_fill_manual(values = col_vals, guide = "none") +
  scale_shape_manual(values = shape_vals, guide = "none") +
  labs(x = "Same-year winter precipitation (mm)", y = NULL) +
  theme_classic(base_size = 13)

p_shan_model <- p_shan_prev + p_shan_same + plot_layout(ncol = 2)
print(p_shan_model)
ggsave(file.path(figures_dir, "p_Shan_coverage.svg"), p_shan_model,
       width = 10, height = 4, units = "in", dpi = 600)


#### 5) Hill_Simpson (q = 2) ####

dd_simp <- long_data %>%
  filter(Metric == "Hill_Simpson") %>%
  drop_na(Value, Plot, Type, same, previous1, same_c, previous1_c) %>%
  mutate(Type = forcats::fct_relevel(Type, "Reserve", "Fragment"))

form_simp_prev  <- Value ~ Type * previous1_c + (1 | Plot)
form_simp_same  <- Value ~ Type * same_c      + (1 | Plot)
form_simp_full  <- Value ~ Type * previous1_c + Type * same_c + (1 | Plot)
form_simp_null  <- Value ~ (1 | Plot)

m_simp_prev_ml <- lmer(form_simp_prev, data = dd_simp, REML = FALSE)
m_simp_same_ml <- lmer(form_simp_same, data = dd_simp, REML = FALSE)
m_simp_full_ml <- lmer(form_simp_full, data = dd_simp, REML = FALSE)
m_simp_null_ml <- lmer(form_simp_null, data = dd_simp, REML = FALSE)

aic_simp <- tibble(
  model   = c("prev_only", "same_only", "prev+same", "null"),
  formula = c(deparse(form_simp_prev), deparse(form_simp_same),
              deparse(form_simp_full), deparse(form_simp_null)),
  AICc    = c(MuMIn::AICc(m_simp_prev_ml), MuMIn::AICc(m_simp_same_ml),
              MuMIn::AICc(m_simp_full_ml), MuMIn::AICc(m_simp_null_ml))
) %>% arrange(AICc)
print(aic_simp)

m_simp_prev_reml <- lmer(form_simp_prev, data = dd_simp, REML = TRUE)
m_simp_same_reml <- lmer(form_simp_same, data = dd_simp, REML = TRUE)
m_simp_full_reml <- lmer(form_simp_full, data = dd_simp, REML = TRUE)

anova_simp_full <- car::Anova(m_simp_full_reml, type = "III")
print(anova_simp_full)

# --- year as a random effect (see Richness section above for rationale) ----
form_simp_full_year <- Value ~ Type * previous1_c + Type * same_c + (1 | Plot) + (1 | year)
m_simp_full_year_reml <- lmer(form_simp_full_year, data = dd_simp, REML = TRUE)
cat("\nSingular fit (year RE model)?", lme4::isSingular(m_simp_full_year_reml), "\n")

anova_simp_full_year <- car::Anova(m_simp_full_year_reml, type = "III")
print(anova_simp_full_year)

compare_simp <- compare_anova(anova_simp_full, anova_simp_full_year, "Hill_Simpson")
print(compare_simp)

r2_simp_full_year <- performance::r2_nakagawa(m_simp_full_year_reml)

cat("\n\n=== COMBINED YEAR-RANDOM-EFFECT COMPARISON, ALL METRICS ===\n")
compare_all_diversity <- bind_rows(compare_rich, compare_shan, compare_simp)
compare_all_diversity <- as.data.frame(compare_all_diversity)
print(compare_all_diversity)

r2_simp_full <- performance::r2_nakagawa(m_simp_full_reml)
print(r2_simp_full)

coef_simp_full <- broom.mixed::tidy(m_simp_full_reml, effects = "fixed", conf.int = TRUE)
print(coef_simp_full)
summary(m_simp_full_reml)

glance_simp_full <- broom.mixed::glance(m_simp_full_reml)
print(glance_simp_full)

r2_mat_simp <- rbind(get_r2(m_simp_prev_reml), get_r2(m_simp_same_reml), get_r2(m_simp_full_reml))
r2_table_simp <- tibble(
  model          = c("prev_only", "same_only", "prev+same"),
  formula        = c(deparse(form_simp_prev), deparse(form_simp_same), deparse(form_simp_full)),
  R2_marginal    = r2_mat_simp[, "R2m"],
  R2_conditional = r2_mat_simp[, "R2c"]
)
simp_m <- r2_table_simp$R2_marginal[r2_table_simp$model == "prev+same"]
simp_c <- r2_table_simp$R2_conditional[r2_table_simp$model == "prev+same"]
r2_table_simp <- r2_table_simp %>%
  mutate(dR2m_vs_full = R2_marginal - simp_m, dR2c_vs_full = R2_conditional - simp_c)
print(r2_table_simp)

# 5.7 Model-based plots for Hill_Simpson
simp_prev_offset <- centering_offset(dd_simp$previous1, dd_simp$previous1_c)
simp_same_offset <- centering_offset(dd_simp$same,      dd_simp$same_c)

prev_seq_simp <- seq(min(dd_simp$previous1_c, na.rm = TRUE),
                     max(dd_simp$previous1_c, na.rm = TRUE), length.out = 200)
same_seq_simp <- seq(min(dd_simp$same_c,      na.rm = TRUE),
                     max(dd_simp$same_c,      na.rm = TRUE), length.out = 200)

pred_simp_prev <- ggpredict(
  m_simp_full_reml,
  terms     = c("previous1_c [prev_seq_simp]", "Type"),
  condition = list(same_c = 0)
) %>% as.data.frame() %>% mutate(x_mm = x + simp_prev_offset)

pred_simp_same <- ggpredict(
  m_simp_full_reml,
  terms     = c("same_c [same_seq_simp]", "Type"),
  condition = list(previous1_c = 0)
) %>% as.data.frame() %>% mutate(x_mm = x + simp_same_offset)

p_simp_prev <- ggplot() +
  geom_point(data = dd_simp, aes(x = previous1, y = Value, color = Type, shape = Type),
             alpha = 0.3, size = 2) +
  geom_ribbon(data = pred_simp_prev,
              aes(x = x_mm, ymin = conf.low, ymax = conf.high, fill = group), alpha = 0.25) +
  geom_line(data = pred_simp_prev,
            aes(x = x_mm, y = predicted, color = group), linewidth = 1.2) +
  scale_color_manual(values = col_vals, guide = "none") +
  scale_fill_manual(values = col_vals, guide = "none") +
  scale_shape_manual(values = shape_vals, guide = "none") +
  labs(x = "Previous-year winter precipitation (mm)", y = "Hill-Simpson (q = 2)") +
  theme_classic()

p_simp_same <- ggplot() +
  geom_point(data = dd_simp, aes(x = same, y = Value, color = Type, shape = Type),
             alpha = 0.3, size = 2) +
  geom_ribbon(data = pred_simp_same,
              aes(x = x_mm, ymin = conf.low, ymax = conf.high, fill = group), alpha = 0.25) +
  geom_line(data = pred_simp_same,
            aes(x = x_mm, y = predicted, color = group), linewidth = 1.2) +
  scale_color_manual(values = col_vals, guide = "none") +
  scale_fill_manual(values = col_vals, guide = "none") +
  scale_shape_manual(values = shape_vals, guide = "none") +
  labs(x = "Same-year winter precipitation (mm)", y = NULL) +
  theme_classic()

p_simp_model <- p_simp_prev + p_simp_same + plot_layout(ncol = 2)
print(p_simp_model)
ggsave(file.path(figures_dir, "p_simp_coverage.png"), p_simp_model,
       width = 10, height = 4, units = "in", dpi = 300)

# =============================================================================
# SECTION 6 — Model diagnostics (Table S5)
#
# Runs Box-Cox + DHARMa diagnostics on the three +year diversity models.
# Richness flags a DHARMa outlier issue driven by a single site (SWI4);
# Section 6b investigates this and confirms results are robust to its
# exclusion (see Appendix S1 note).
# =============================================================================

dir.create(file.path(figures_dir, "diagnostics"), showWarnings = FALSE)

run_diagnostics <- function(model, metric_name, diag_dat) {
  
  diag_dat <- as.data.frame(diag_dat)
  y <- diag_dat[["Value"]]
  
  cat("\n==============================\n")
  cat("Diagnostics:", metric_name, "\n")
  cat("==============================\n")
  
  # Box-Cox optimal lambda
  lambdas <- seq(-2, 2, by = 0.1)
  log_liks <- sapply(lambdas, function(lam) {
    y_trans <- if (abs(lam) < 1e-10) log(y) else (y^lam - 1) / lam
    sum(dnorm(y_trans, mean(y_trans), sd(y_trans), log = TRUE)) + (lam - 1) * sum(log(y))
  })
  lambda_opt <- lambdas[which.max(log_liks)]
  cat("Box-Cox optimal lambda:", round(lambda_opt, 3), " (log = 0, no transform = 1)\n")
  
  # Raw vs. log distribution check
  png(file.path(figures_dir, "diagnostics", paste0(metric_name, "_distribution_check.png")),
      width = 800, height = 400, res = 120)
  par(mfrow = c(1, 2))
  hist(y, main = paste(metric_name, "- raw"), xlab = "Value", col = "steelblue", border = "white")
  hist(log(y + 0.001), main = paste(metric_name, "- log"), xlab = "log(Value)", col = "coral", border = "white")
  par(mfrow = c(1, 1))
  dev.off()
  
  # DHARMa
  sim_res      <- DHARMa::simulateResiduals(model, n = 1000, plot = FALSE)
  disp_test    <- DHARMa::testDispersion(sim_res,  plot = FALSE)
  outlier_test <- DHARMa::testOutliers(sim_res,    plot = FALSE)
  unif_test    <- DHARMa::testUniformity(sim_res,  plot = FALSE)
  
  png(file.path(figures_dir, "diagnostics", paste0(metric_name, "_dharma_residuals.png")),
      width = 900, height = 500, res = 120)
  plot(sim_res, main = metric_name)
  dev.off()
  
  cat("DHARMa dispersion p =", round(disp_test$p.value,    4), "\n")
  cat("DHARMa outlier p =",    round(outlier_test$p.value, 4), "\n")
  cat("DHARMa uniformity p =", round(unif_test$p.value,    4), "\n")
  
  perf_plot <- performance::check_model(model)
  ggplot2::ggsave(
    file.path(figures_dir, "diagnostics", paste0(metric_name, "_check_model.png")),
    plot = plot(perf_plot), width = 12, height = 10, dpi = 150
  )
  
  list(
    summary = tibble::tibble(
      metric           = metric_name,
      boxcox_lambda    = round(lambda_opt,           3),
      dharma_disp_p    = round(disp_test$p.value,    4),
      dharma_outlier_p = round(outlier_test$p.value, 4),
      dharma_uniform_p = round(unif_test$p.value,    4)
    ),
    sim_res = sim_res   # kept for downstream outlier-row lookup, e.g. Richness below
  )
}

diag_rich <- run_diagnostics(m_rich_full_year_reml, "Richness",     dd_rich)
diag_shan <- run_diagnostics(m_shan_full_year_reml, "Hill_Shannon", dd_shan)
diag_simp <- run_diagnostics(m_simp_full_year_reml, "Hill_Simpson", dd_simp)

diag_summary <- bind_rows(diag_rich$summary, diag_shan$summary, diag_simp$summary)
print(diag_summary)
cat("\nDiagnostic plots saved to figures/diagnostics/\n")

# =============================================================================
# SECTION 6b — Richness outlier investigation (SWI4 sensitivity check)
#
# The Richness model's DHARMa outlier test was significant (see diag_summary
# above). This identifies which site is responsible, confirms it via Cook's
# distance, and re-fits excluding it to confirm results are unaffected.
# =============================================================================

# Which specific observations were flagged?
outlier_rows <- which(diag_rich$sim_res$scaledResiduals %in% c(0, 1))
cat("\nFlagged outlier rows (Richness):\n")
print(dd_rich[outlier_rows, c("Plot", "year", "Type", "Value")])

# Cook's distance by Plot -- confirms whether the flagged site is also
# unusually influential (use lme4::lmer explicitly; lmerTest's class can
# break influence.ME's deviance extraction)
m_rich_clean <- lme4::lmer(
  Value ~ Type * previous1_c + Type * same_c + (1 | Plot) + (1 | year),
  data = dd_rich, REML = TRUE
)
infl_rich <- influence.ME::influence(m_rich_clean, group = "Plot")

cooks_df <- tibble::tibble(
  Plot    = levels(factor(dd_rich$Plot)),
  cooks_d = cooks.distance(infl_rich)
) %>% arrange(desc(cooks_d))
cat("\nTop 5 most influential sites (Richness model):\n")
print(head(cooks_df, 5))

# Sensitivity check: refit excluding the flagged site
influential_site <- cooks_df$Plot[1]
cat("\nRefitting Richness model excluding", influential_site, "...\n")

dd_rich_sensitivity <- dd_rich %>% filter(Plot != influential_site)
m_rich_sensitivity <- lme4::lmer(
  Value ~ Type * previous1_c + Type * same_c + (1 | Plot) + (1 | year),
  data = dd_rich_sensitivity, REML = TRUE
)
cat("Singular fit?", lme4::isSingular(m_rich_sensitivity), "\n\n")
print(car::Anova(m_rich_sensitivity, type = "III"))

sim_sensitivity <- DHARMa::simulateResiduals(m_rich_sensitivity, n = 1000)
cat("\n--- Diagnostics after excluding", influential_site, "---\n")
print(DHARMa::testOutliers(sim_sensitivity, plot = FALSE))
print(DHARMa::testUniformity(sim_sensitivity, plot = FALSE))




#### FRAGMENTS ONLY ####

get_r2_safe <- function(m) {
  r2 <- suppressWarnings(MuMIn::r.squaredGLMM(m))
  c(R2m = as.numeric(r2[1, "R2m"]), R2c = as.numeric(r2[1, "R2c"]))
}

run_frag_models <- function(metric_name, dat = long_data) {
  
  dd <- dat %>%
    dplyr::filter(Metric == metric_name, Type == "Fragment") %>%
    tidyr::drop_na(Value, Plot, year, same, previous1, same_c, previous1_c)
  
  message("\n==============================")
  message("Fragments-only: ", metric_name)
  message("N rows = ", nrow(dd), " | N plots = ", dplyr::n_distinct(dd$Plot))
  message("==============================")
  
  form_prev <- Value ~ previous1_c + (1 | Plot) + (1 | year)
  form_same <- Value ~ same_c      + (1 | Plot) + (1 | year)
  form_full <- Value ~ previous1_c + same_c + (1 | Plot) + (1 | year)
  form_null <- Value ~ (1 | Plot) + (1 | year)   # null model: random effects only, no fixed effects
  
  m_prev_ml <- lmer(form_prev, data = dd, REML = FALSE)
  m_same_ml <- lmer(form_same, data = dd, REML = FALSE)
  m_full_ml <- lmer(form_full, data = dd, REML = FALSE)
  m_null_ml <- lmer(form_null, data = dd, REML = FALSE)
  
  aic_tab <- tibble::tibble(
    Metric  = metric_name,
    model   = c("prev_only", "same_only", "prev+same", "null"),
    formula = c(deparse(form_prev), deparse(form_same), deparse(form_full), deparse(form_null)),
    AICc    = c(MuMIn::AICc(m_prev_ml), MuMIn::AICc(m_same_ml),
                MuMIn::AICc(m_full_ml), MuMIn::AICc(m_null_ml))
  ) %>% dplyr::arrange(AICc)
  print(aic_tab)
  
  m_full_reml <- lmer(form_full, data = dd, REML = TRUE)
  cat("Singular fit?", lme4::isSingular(m_full_reml), "\n")
  
  anova_full <- car::Anova(m_full_reml, type = "III")
  print(anova_full)
  
  r2_full <- get_r2_safe(m_full_reml)
  r2_tab <- tibble::tibble(
    Metric         = metric_name,
    model          = "prev+same",
    R2_marginal    = r2_full["R2m"],
    R2_conditional = r2_full["R2c"]
  )
  print(r2_tab)
  
  fe <- broom.mixed::tidy(m_full_reml, effects = "fixed", conf.int = TRUE)
  print(fe)
  
  # Use safe centering offsets for this subset
  prev_off <- centering_offset(dd$previous1, dd$previous1_c)
  same_off <- centering_offset(dd$same,      dd$same_c)
  
  prev_seq <- seq(min(dd$previous1_c, na.rm = TRUE),
                  max(dd$previous1_c, na.rm = TRUE), length.out = 200)
  same_seq <- seq(min(dd$same_c,      na.rm = TRUE),
                  max(dd$same_c,      na.rm = TRUE), length.out = 200)
  
  pred_prev <- ggeffects::ggpredict(
    m_full_reml,
    terms     = c("previous1_c [prev_seq]"),
    condition = list(same_c = 0)
  ) %>% as.data.frame() %>% dplyr::mutate(x_mm = x + prev_off)
  
  pred_same <- ggeffects::ggpredict(
    m_full_reml,
    terms     = c("same_c [same_seq]"),
    condition = list(previous1_c = 0)
  ) %>% as.data.frame() %>% dplyr::mutate(x_mm = x + same_off)
  
  p_prev <- ggplot2::ggplot() +
    ggplot2::geom_point(data = dd, ggplot2::aes(x = previous1, y = Value),
                        color = "gray40", alpha = 0.35, size = 1.8) +
    ggplot2::geom_ribbon(data = pred_prev,
                         ggplot2::aes(x = x_mm, ymin = conf.low, ymax = conf.high),
                         alpha = 0.25) +
    ggplot2::geom_line(data = pred_prev,
                       ggplot2::aes(x = x_mm, y = predicted), linewidth = 1.2) +
    ggplot2::theme_classic() +
    ggplot2::labs(x = "Previous-year winter precipitation (mm)",
                  y = paste0(metric_name, " (fragments only)"))
  
  p_same <- ggplot2::ggplot() +
    ggplot2::geom_point(data = dd, ggplot2::aes(x = same, y = Value),
                        color = "gray40", alpha = 0.35, size = 1.8) +
    ggplot2::geom_ribbon(data = pred_same,
                         ggplot2::aes(x = x_mm, ymin = conf.low, ymax = conf.high),
                         alpha = 0.25) +
    ggplot2::geom_line(data = pred_same,
                       ggplot2::aes(x = x_mm, y = predicted), linewidth = 1.2) +
    ggplot2::theme_classic() +
    ggplot2::labs(x = "Same-year winter precipitation (mm)", y = NULL)
  
  p_both <- p_prev + p_same + patchwork::plot_layout(ncol = 2)
  print(p_both)
  
  safe_metric <- gsub("[^A-Za-z0-9_]+", "_", metric_name)
  ggplot2::ggsave(
    filename = paste0("fragOnly_", safe_metric, "_precip.png"),
    plot = p_both, width = 10, height = 4, units = "in", dpi = 300
  )
  
  list(data = dd, aic = aic_tab, anova = broom::tidy(anova_full),
       fixed = fe, r2 = r2_tab, model_reml = m_full_reml)
}

frag_results <- list(
  Richness     = run_frag_models("Richness"),
  Hill_Shannon = run_frag_models("Hill_Shannon"),
  Hill_Simpson = run_frag_models("Hill_Simpson")
)


#### RESERVES ONLY ####

run_reserve_models <- function(metric_name, dat = long_data) {
  
  dd <- dat %>%
    dplyr::filter(Metric == metric_name, Type == "Reserve") %>%   # FIXED: was "Fragment"
    tidyr::drop_na(Value, Plot, year, same, previous1, same_c, previous1_c)
  
  message("\n==============================")
  message("Reserves-only: ", metric_name)
  message("N rows = ", nrow(dd), " | N plots = ", dplyr::n_distinct(dd$Plot))
  message("==============================")
  
  form_prev <- Value ~ previous1_c + (1 | Plot) + (1 | year)
  form_same <- Value ~ same_c      + (1 | Plot) + (1 | year)
  form_full <- Value ~ previous1_c + same_c + (1 | Plot) + (1 | year)
  form_null <- Value ~ (1 | Plot) + (1 | year)   # null model: random effects only, no fixed effects
  
  m_prev_ml <- lmer(form_prev, data = dd, REML = FALSE)
  m_same_ml <- lmer(form_same, data = dd, REML = FALSE)
  m_full_ml <- lmer(form_full, data = dd, REML = FALSE)
  m_null_ml <- lmer(form_null, data = dd, REML = FALSE)
  
  aic_tab <- tibble::tibble(
    Metric  = metric_name,
    model   = c("prev_only", "same_only", "prev+same", "null"),
    formula = c(deparse(form_prev), deparse(form_same), deparse(form_full), deparse(form_null)),
    AICc    = c(MuMIn::AICc(m_prev_ml), MuMIn::AICc(m_same_ml),
                MuMIn::AICc(m_full_ml), MuMIn::AICc(m_null_ml))
  ) %>% dplyr::arrange(AICc)
  print(aic_tab)
  
  m_full_reml <- lmer(form_full, data = dd, REML = TRUE)
  cat("Singular fit?", lme4::isSingular(m_full_reml), "\n")
  anova_full <- car::Anova(m_full_reml, type = "III")
  print(anova_full)
  
  r2_full <- get_r2_safe(m_full_reml)
  r2_tab <- tibble::tibble(
    Metric         = metric_name,
    model          = "prev+same",
    R2_marginal    = r2_full["R2m"],
    R2_conditional = r2_full["R2c"]
  )
  print(r2_tab)
  
  fe <- broom.mixed::tidy(m_full_reml, effects = "fixed", conf.int = TRUE)
  print(fe)
  
  # Use safe centering offsets for this subset
  prev_off <- centering_offset(dd$previous1, dd$previous1_c)
  same_off <- centering_offset(dd$same,      dd$same_c)
  
  prev_seq <- seq(min(dd$previous1_c, na.rm = TRUE),
                  max(dd$previous1_c, na.rm = TRUE), length.out = 200)
  same_seq <- seq(min(dd$same_c,      na.rm = TRUE),
                  max(dd$same_c,      na.rm = TRUE), length.out = 200)
  
  pred_prev <- ggeffects::ggpredict(
    m_full_reml,
    terms     = c("previous1_c [prev_seq]"),
    condition = list(same_c = 0)
  ) %>% as.data.frame() %>% dplyr::mutate(x_mm = x + prev_off)
  
  pred_same <- ggeffects::ggpredict(
    m_full_reml,
    terms     = c("same_c [same_seq]"),
    condition = list(previous1_c = 0)
  ) %>% as.data.frame() %>% dplyr::mutate(x_mm = x + same_off)
  
  p_prev <- ggplot2::ggplot() +
    ggplot2::geom_point(data = dd, ggplot2::aes(x = previous1, y = Value),
                        color = "gray40", alpha = 0.35, size = 2) +
    ggplot2::geom_ribbon(data = pred_prev,
                         ggplot2::aes(x = x_mm, ymin = conf.low, ymax = conf.high),
                         fill = "darkgreen", alpha = 0.25) +
    ggplot2::geom_line(data = pred_prev,
                       ggplot2::aes(x = x_mm, y = predicted),
                       color = "darkgreen", linewidth = 1.2) +
    ggplot2::theme_classic(base_size = 13) +
    ggplot2::labs(x = "Previous-year winter precipitation (mm)",
                  y = paste0(metric_name, " (reserves only)"))
  
  p_same <- ggplot2::ggplot() +
    ggplot2::geom_point(data = dd, ggplot2::aes(x = same, y = Value),
                        color = "gray40", alpha = 0.35, size = 2) +
    ggplot2::geom_ribbon(data = pred_same,
                         ggplot2::aes(x = x_mm, ymin = conf.low, ymax = conf.high),
                         fill = "darkgreen", alpha = 0.25) +
    ggplot2::geom_line(data = pred_same,
                       ggplot2::aes(x = x_mm, y = predicted),
                       color = "darkgreen", linewidth = 1.2) +
    ggplot2::theme_classic(base_size = 13) +
    ggplot2::labs(x = "Same-year winter precipitation (mm)", y = NULL)
  
  p_both <- p_prev + p_same + patchwork::plot_layout(ncol = 2)
  print(p_both)
  
  safe_metric <- gsub("[^A-Za-z0-9_]+", "_", metric_name)
  ggplot2::ggsave(
    filename = paste0("ReserveOnly_", safe_metric, "_precip.png"),
    plot = p_both, width = 10, height = 4, units = "in", dpi = 300
  )
  
  list(data = dd, aic = aic_tab, anova = broom::tidy(anova_full),
       fixed = fe, r2 = r2_tab, model_reml = m_full_reml)
}

reserve_results <- list(
  Richness     = run_reserve_models("Richness"),
  Hill_Shannon = run_reserve_models("Hill_Shannon"),
  Hill_Simpson = run_reserve_models("Hill_Simpson")
)

reserve_results$Richness$anova
reserve_results$Hill_Shannon$anova
reserve_results$Hill_Simpson$anova


# =============================================================================
# 6-panel figures by Type
# =============================================================================

type_cols <- c(Fragment = "gray52", Reserve = "springgreen4")

metric_titles <- c(
  Richness     = "Richness (q = 0)",
  Hill_Shannon = "Hill–Shannon (q = 1)",
  Hill_Simpson = "Hill–Simpson (q = 2)"
)

one_panel <- function(metric_name, type_name, which = c("prev", "same"),
                      show_row_title = FALSE, dat = long_data) {
  which <- match.arg(which)
  
  dd <- dat %>%
    filter(Metric == metric_name, Type == type_name) %>%
    drop_na(Value, Plot, previous1, same, previous1_c, same_c)
  
  m <- lmer(Value ~ previous1_c + same_c + (1 | Plot), data = dd, REML = TRUE)
  
  # Safe centering offsets for this type/metric subset
  prev_off <- centering_offset(dd$previous1, dd$previous1_c)
  same_off <- centering_offset(dd$same,      dd$same_c)
  
  if (which == "prev") {
    p_seq <- seq(min(dd$previous1_c, na.rm = TRUE),
                 max(dd$previous1_c, na.rm = TRUE), length.out = 200)
    pred <- ggpredict(m, terms = "previous1_c [p_seq]",
                      condition = list(same_c = 0)) %>%
      as.data.frame() %>%
      mutate(x_mm = x + prev_off)
    pts <- dd %>% transmute(x = previous1, Value = Value)
  } else {
    s_seq <- seq(min(dd$same_c, na.rm = TRUE),
                 max(dd$same_c, na.rm = TRUE), length.out = 200)
    pred <- ggpredict(m, terms = "same_c [s_seq]",
                      condition = list(previous1_c = 0)) %>%
      as.data.frame() %>%
      mutate(x_mm = x + same_off)
    pts <- dd %>% transmute(x = same, Value = Value)
  }
  
  ggplot() +
    geom_point(data = pts, aes(x = x, y = Value),
               color = "gray40", alpha = 0.35, size = 1.8) +
    geom_ribbon(data = pred, aes(x = x_mm, ymin = conf.low, ymax = conf.high),
                fill = type_cols[[type_name]], alpha = 0.20) +
    geom_line(data = pred, aes(x = x_mm, y = predicted),
              color = type_cols[[type_name]], linewidth = 1.1) +
    theme_classic(base_size = 13) +
    theme(axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          plot.title   = element_text(face = "bold", hjust = 0)) +
    labs(title = if (show_row_title) metric_titles[[metric_name]] else NULL)
}

make_6panel_one_type <- function(type_name, dat = long_data) {
  panels <- list(
    one_panel("Richness",     type_name, "prev", show_row_title = TRUE,  dat = dat),
    one_panel("Richness",     type_name, "same", show_row_title = FALSE, dat = dat),
    one_panel("Hill_Shannon", type_name, "prev", show_row_title = TRUE,  dat = dat),
    one_panel("Hill_Shannon", type_name, "same", show_row_title = FALSE, dat = dat),
    one_panel("Hill_Simpson", type_name, "prev", show_row_title = TRUE,  dat = dat),
    one_panel("Hill_Simpson", type_name, "same", show_row_title = FALSE, dat = dat)
  )
  
  p_main <- wrap_plots(panels, ncol = 2)
  
  p_labels <- ggplot() +
    theme_void() +
    annotate("text", x = 0.25, y = 0.5,
             label = "WP[y[0-1]]~'(mm)'", parse = TRUE, size = 5) +
    annotate("text", x = 0.75, y = 0.5,
             label = "WP[y[0]]~'(mm)'",   parse = TRUE, size = 5) +
    xlim(0, 1) + ylim(0, 1)
  
  (p_main / p_labels + plot_layout(heights = c(20, 1))) +
    plot_annotation(title = paste0(type_name, "s")) &
    theme(plot.title = element_text(face = "bold", size = 16, hjust = 0))
}

p_frag <- make_6panel_one_type("Fragment", long_data)
p_res  <- make_6panel_one_type("Reserve",  long_data)

p_frag
p_res

ggsave(file.path(figures_dir, "Fig_Fragment_6panel_WP.png"), p_frag, width = 10, height = 12, dpi = 300)
ggsave(file.path(figures_dir, "Fig_Reserve_6panel_WP.png"),  p_res,  width = 10, height = 12, dpi = 300)
ggsave(file.path(figures_dir, "Fig_Fragment_6panel_WP.svg"), p_frag, width = 10, height = 12)
ggsave(file.path(figures_dir, "Fig_Reserve_6panel_WP.svg"),  p_res,  width = 10, height = 12)


# =============================================================================
# CONSOLIDATED EXCEL EXPORT — single workbook, all models
# =============================================================================

# Helper: add a Metric column to all tables for traceability
tag <- function(df, metric) dplyr::mutate(df, Metric = metric, .before = 1)

writexl::write_xlsx(
  list(
    
    # ── AIC tables ──────────────────────────────────────────────────────────
    AICc_Richness    = tag(aic_rich, "Richness"),
    AICc_HillShannon = tag(aic_shan, "Hill_Shannon"),
    AICc_HillSimpson = tag(aic_simp, "Hill_Simpson"),
    
    # ── Year-random-effect comparison (Type III ANOVA + AICc) ──────────────
    YearRE_ANOVA_Comparison = compare_all_diversity,
    YearRE_AICc_Richness    = aic_rich_year,
    YearRE_AICc_HillShannon = aic_shan_year,
    
    # ── Type III ANOVA (full models, all types combined) ────────────────────
    ANOVA_Richness    = tag(broom::tidy(anova_rich_full), "Richness"),
    ANOVA_HillShannon = tag(broom::tidy(anova_shan_full), "Hill_Shannon"),
    ANOVA_HillSimpson = tag(broom::tidy(anova_simp_full), "Hill_Simpson"),
    
    # ── Fixed effects (full models, all types combined) ─────────────────────
    FE_Richness     = tag(coef_rich_full, "Richness"),
    FE_HillShannon  = tag(coef_shan_full, "Hill_Shannon"),
    FE_HillSimpson  = tag(coef_simp_full, "Hill_Simpson"),
    
    # ── R² tables (all types combined) ──────────────────────────────────────
    R2_Richness     = tag(r2_table_rich, "Richness"),
    R2_HillShannon  = tag(r2_table_shan, "Hill_Shannon"),
    R2_HillSimpson  = tag(r2_table_simp, "Hill_Simpson"),
    
    # ── Fragments-only results ───────────────────────────────────────────────
    FragAICc  = dplyr::bind_rows(lapply(frag_results,    `[[`, "aic")),
    FragANOVA = dplyr::bind_rows(lapply(frag_results,    `[[`, "anova"), .id = "Metric"),
    FragFE    = dplyr::bind_rows(lapply(frag_results,    `[[`, "fixed"), .id = "Metric"),
    FragR2    = dplyr::bind_rows(lapply(frag_results,    `[[`, "r2")),
    
    # ── Reserves-only results ────────────────────────────────────────────────
    ResAICc   = dplyr::bind_rows(lapply(reserve_results, `[[`, "aic")),
    ResANOVA  = dplyr::bind_rows(lapply(reserve_results, `[[`, "anova"), .id = "Metric"),
    ResFE     = dplyr::bind_rows(lapply(reserve_results, `[[`, "fixed"), .id = "Metric"),
    ResR2     = dplyr::bind_rows(lapply(reserve_results, `[[`, "r2")),
    
    # ── DHARMa diagnostics ───────────────────────────────────────────────────
    Diagnostics_DHARMa = diag_summary
  ),
  path = file.path(results_dir, "All_model_results_COVERAGE.xlsx")
)

cat("\nAll results exported to results/All_model_results_COVERAGE.xlsx\n")

## =============================================================================
## SECTION — Sensitivity check: diversity models with indicator species
## removed (Table S13/S14). Append to the END of R-05_bee_diversity.R,
## after the main analysis has fully run (reuses target_cov, df_analysis,
## and the (1|Plot) + (1|year) model structure established above).
##
## Coverage-based rarefaction (iNEXT::estimateD) must be RE-RUN on the
## reduced species pool, not filtered post-hoc from the main results,
## since removing species changes each assemblage's sample coverage.
## =============================================================================

indicators <- readRDS(file.path(cleaned_dir, "indicator_species.rds"))
cat("\nIndicator species to remove:", length(indicators), "\n")

# --- Rebuild the abundance/coverage pipeline, indicators excluded ----------
allbees_noind <- df_analysis %>%
  rename(Plot = fieldNumber) %>%
  mutate(
    year      = as.factor(year),
    Count     = as.numeric(Count),
    plot_year = paste(Plot, year, sep = "_")
  ) %>%
  filter(!scientificName %in% indicators)

cat("Rows before exclusion:", nrow(df_analysis),
    "| after:", nrow(allbees_noind), "\n")

comm_noind <- allbees_noind %>%
  group_by(plot_year, Plot, year, Type, scientificName) %>%
  summarise(n = sum(Count), .groups = "drop") %>%
  pivot_wider(names_from = scientificName, values_from = n, values_fill = 0)

meta_noind <- comm_noind %>% dplyr::select(plot_year, Plot, year, Type)
species_cols_noind <- setdiff(names(comm_noind), c("plot_year","Plot","year","Type"))

abund_list_noind <- apply(
  comm_noind[, species_cols_noind, drop = FALSE], 1,
  function(z) { z <- as.numeric(z); z[z > 0] }
)
names(abund_list_noind) <- comm_noind$plot_year

# Same target_cov as the main analysis -- direct, like-for-like comparison
est_noind <- iNEXT::estimateD(
  abund_list_noind, q = c(0, 1, 2), datatype = "abundance",
  base = "coverage", level = target_cov
) %>% as_tibble()

long_cov_noind <- est_noind %>%
  transmute(plot_year = Assemblage, Order.q, SC, qD) %>%
  left_join(meta_noind, by = "plot_year") %>%
  mutate(Metric = dplyr::recode(Order.q, `0`="Richness", `1`="Hill_Shannon", `2`="Hill_Simpson")) %>%
  dplyr::select(Plot, Type, year, plot_year, Metric, Value = qD, common_coverage = SC) %>%
  left_join(precipitation_yearly %>% dplyr::select(year, same, previous1), by = "year") %>%
  mutate(same_c = same - mean_same, previous1_c = previous1 - mean_prev)

# --- Fit the SAME model structure used throughout (Type * precip x2, +year) -
fit_noind_model <- function(metric_name) {
  dd <- long_cov_noind %>%
    filter(Metric == metric_name) %>%
    drop_na(Value, Plot, Type, same, previous1, same_c, previous1_c) %>%
    mutate(Type = forcats::fct_relevel(Type, "Reserve", "Fragment"))
  
  m <- lmer(Value ~ Type * previous1_c + Type * same_c + (1 | Plot) + (1 | year),
            data = dd, REML = TRUE)
  cat("\n---", metric_name, "(indicators removed) singular fit?",
      lme4::isSingular(m), "---\n")
  a <- car::Anova(m, type = "III")
  print(a)
  list(model = m, anova = a, data = dd)
}

noind_rich <- fit_noind_model("Richness")
noind_shan <- fit_noind_model("Hill_Shannon")
noind_simp <- fit_noind_model("Hill_Simpson")

# --- Side-by-side comparison: full dataset vs. indicators-removed ----------
compare_noind <- function(anova_full, anova_noind, metric_name) {
  a1 <- as.data.frame(anova_full)  %>% tibble::rownames_to_column("term")
  a2 <- as.data.frame(anova_noind) %>% tibble::rownames_to_column("term")
  dplyr::full_join(
    a1 %>% dplyr::select(term, Chisq_full_data = Chisq, P_full_data = `Pr(>Chisq)`),
    a2 %>% dplyr::select(term, Chisq_no_indicators = Chisq, P_no_indicators = `Pr(>Chisq)`),
    by = "term"
  ) %>% mutate(Metric = metric_name, .before = 1)
}

compare_indicators_all <- bind_rows(
  compare_noind(anova_rich_full_year, noind_rich$anova, "Richness"),
  compare_noind(anova_shan_full_year, noind_shan$anova, "Hill_Shannon"),
  compare_noind(anova_simp_full_year, noind_simp$anova, "Hill_Simpson")
)
compare_indicators_all <- as.data.frame(compare_indicators_all)
cat("\n=== Table S13/S14: full data vs. indicator species removed ===\n")
print(compare_indicators_all)