## =============================================================================
## R-07_body_size.R
##
## Purpose : Test Prediction 4 — assemblage body size increases with winter
##           precipitation. Coverage-standardized abundance-weighted and
##           presence-weighted mean intertegular distance (ITD) as a proxy
##           for body size. Mixed-effects models with WPy0, WPy0-1, site type,
##           and interactions. Additive and interaction model comparison.
##           Type-split sensitivity models also reported.
##
## Inputs  : data/cleaned/df_analysis.csv       — filtered occurrences with
##                                                 itd_species_mean already joined
##                                                 (generated by R-01)
##           data/cleaned/precipyrs.csv         — annual winter totals + lags
##                                                 (generated by R-02)
##           data/cleaned/target_coverage.rds   — shared coverage target scalar
##                                                 (generated by R-01)
##
## Outputs : figures/itd_weighted_model.svg     — weighted ITD ~ precip panels
##           figures/itd_unweighted_model.svg   — unweighted ITD ~ precip panels
##           figures/diagnostics/               — DHARMa + check_model plots
##           results/ITD_model_results.xlsx     — model summaries and stats
##           results/diagnostics_dharma_itd.xlsx — DHARMa test summary
##
## Note    : itd_species_mean in df_analysis.csv is the species-level mean ITD
##           (mm) used in all body size analyses. Values are from traits.csv,
##           derived from field measurements by the authors and collaborators.
##
## Author  : [Your name]
## Date    : [Date]
## =============================================================================

suppressPackageStartupMessages({
  library(tidyverse)
  library(lme4)
  library(lmerTest)
  library(car)
  library(performance)
  library(forcats)
  library(patchwork)
  library(iNEXT)
  library(vegan)
  library(purrr)
  library(writexl)
  library(DHARMa)
  library(MASS)
})

set.seed(123)

## File paths
figures_dir <- "figures"
results_dir <- "results"
cleaned_dir <- "data/cleaned"
raw_dir     <- "data/raw"

dir.create(file.path(figures_dir, "diagnostics"), showWarnings = FALSE)

# =============================================================================
# SECTION 1 — Settings
# =============================================================================

survey_years <- c(2011, 2012, 2015, 2016, 2022, 2023, 2024)
l_types      <- c("Fragment", "Reserve")
n_iter_sc    <- 999

# Load shared coverage target from R-01
target_SC <- readRDS(file.path(cleaned_dir, "target_coverage.rds"))
cat("Loaded target coverage from R-01:", round(target_SC, 4), "\n")

indicators <- c("Halictus farinosus", "Lasioglossum sisymbrii",
                "Augochlorella pomoniella", "Eucera dorsata", "Eucera tricinctella",
                "Lasioglossum punctatoventre", "Lasioglossum robustum",
                "Megachile subnigra", "Melissodes plumosus", "Anthidium jocosum",
                "Ceratina nanula", "Lasioglossum MSN turgiventre",
                "Lasioglossum perparvum", "Melissodes tessellatus",
                "Micralictoides ruficaudus", "Andrena osmioides",
                "Perdita interrupta interrupta", "Dianthidium dubium",
                "Dufourea sandhouseae", "Andrena ablegata",
                "Dianthidium pudicum consimile", "Megachile coquilletti",
                "Osmia gabrielis", "Anthophorula torticornis", "Bombus vosnesenskii",
                "Lasioglossum titusi", "Lasioglossum actinosum",
                "Lasioglossum stictaspis complex", "Osmia granulosa",
                "Halictus ligatus", "Bombus californicus", "Osmia clarescens",
                "Hylaeus mesillae cressoni", "Diadasia opuntiae",
                "Calliopsis obscurella", "Hesperapis fuchsi", "Melissodes stearnsi",
                "Ashmeadiella californica", "Dufourea rhamni", "Andrena atypica",
                "Lasioglossum perichlarum", "Megachile onobrychidis",
                "Dufourea brevicornis", "Melissodes velutinus", "Diadasia ochracea",
                "Perdita claypolei australior")

# =============================================================================
# SECTION 2 — Load data
#
# df_analysis already has itd_species_mean joined per specimen from R-01.
# No need to load separate ITD files.
# =============================================================================

df_analysis <- read.csv(file.path(cleaned_dir, "df_analysis.csv"),
                        check.names = FALSE)

precip_raw <- read.csv(file.path(cleaned_dir, "precipyrs.csv"),
                       check.names = FALSE)
names(precip_raw) <- make.names(names(precip_raw), unique = TRUE)

# =============================================================================
# SECTION 3 — Filter for bowl-only analysis dataset
# =============================================================================

allbees_bowl <- df_analysis %>%
  mutate(
    year  = as.integer(year),
    Count = as.numeric(individualCount)
  ) %>%
  filter(
   # !scientificName  %in% indicators,   # remove to test indicator species effect
  ) %>%
  mutate(Type = factor(Type))

# =============================================================================
# SECTION 4 — Precipitation: center predictors
# =============================================================================

precip_itd <- precip_raw %>%
  transmute(
    year      = as.integer(year),
    same      = same,
    previous1 = previous1
  ) %>%
  filter(year %in% survey_years)

stopifnot(all(sort(unique(precip_itd$year)) == sort(survey_years)))
stopifnot(all((precip_itd %>% count(year))$n == 1))

mean_same <- mean(precip_itd$same,      na.rm = TRUE)
mean_prev <- mean(precip_itd$previous1, na.rm = TRUE)

precip_itd <- precip_itd %>%
  mutate(
    same_c      = same      - mean_same,
    previous1_c = previous1 - mean_prev
  )

# =============================================================================
# SECTION 5 — Build plot-year species table for coverage-based ITD
# =============================================================================

body_long <- allbees_bowl %>%
  filter(!is.na(itd)) %>%
  group_by(fieldNumber, year, Type, scientificName) %>%
  summarise(
    Count = sum(individualCount, na.rm = TRUE),
    itd   = mean(itd, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  rename(Plot = fieldNumber)

# =============================================================================
# SECTION 6 — Coverage-based ITD rarefaction helpers
# =============================================================================

# WEIGHTED: abundance-weighted mean ITD
calc_itd_rarefied <- function(counts, itd_vec) {
  counts   <- as.numeric(counts)
  N        <- sum(counts)
  info     <- iNEXT::DataInfo(counts, datatype = "abundance")
  chat_obs <- as.numeric(info$SC)

  if (is.na(chat_obs) || N <= 1) {
    return(list(aw_itd = NA_real_, coverage_obs = chat_obs,
                N = N, n_target = NA_real_))
  }

  n_target <- if (chat_obs <= target_SC) N else N * (target_SC / chat_obs)
  n_target <- max(1L, min(N, round(n_target)))

  aw_vals <- numeric(n_iter_sc)
  for (i in seq_len(n_iter_sc)) {
    rar <- vegan::rrarefy(counts, sample = n_target)
    rel <- rar / sum(rar)
    aw_vals[i] <- sum(rel * itd_vec, na.rm = TRUE)
  }

  list(aw_itd = mean(aw_vals, na.rm = TRUE), coverage_obs = chat_obs,
       N = N, n_target = n_target)
}

# UNWEIGHTED: presence-weighted mean ITD
calc_itd_rarefied_unw <- function(counts, itd_vec) {
  counts   <- as.numeric(counts)
  N        <- sum(counts)
  info     <- iNEXT::DataInfo(counts, datatype = "abundance")
  chat_obs <- as.numeric(info$SC)

  if (is.na(chat_obs) || N <= 1) {
    return(list(uw_itd = NA_real_, coverage_obs = chat_obs,
                N = N, n_target = NA_real_))
  }

  n_target <- if (chat_obs <= target_SC) N else N * (target_SC / chat_obs)
  n_target <- max(1L, min(N, round(n_target)))

  uw_vals <- numeric(n_iter_sc)
  for (i in seq_len(n_iter_sc)) {
    rar  <- vegan::rrarefy(counts, sample = n_target)
    pres <- rar > 0
    uw_vals[i] <- if (!any(pres)) NA_real_ else mean(itd_vec[pres], na.rm = TRUE)
  }

  list(uw_itd = mean(uw_vals, na.rm = TRUE), coverage_obs = chat_obs,
       N = N, n_target = n_target)
}

# =============================================================================
# SECTION 7 — Coverage-standardized ITD per plot-year
# =============================================================================

cat("Computing coverage-standardized weighted ITD (999 iterations)...\n")

itd_cov_tbl <- body_long %>%
  group_by(Plot, year, Type) %>%
  group_modify(~ {
    out <- calc_itd_rarefied(.x$Count, .x$itd)
    tibble(avg_itd_cov = out$aw_itd, coverage = out$coverage_obs,
           N_total = out$N, n_target = out$n_target)
  }) %>%
  ungroup()

cat("Computing coverage-standardized unweighted ITD...\n")

itd_cov_unw_tbl <- body_long %>%
  group_by(Plot, year, Type) %>%
  group_modify(~ {
    out <- calc_itd_rarefied_unw(.x$Count, .x$itd)
    tibble(avg_itd_cov_unw = out$uw_itd, coverage = out$coverage_obs,
           N_total = out$N, n_target = out$n_target)
  }) %>%
  ungroup()

itd_weighted   <- itd_cov_tbl     %>% left_join(precip_itd, by = "year")
itd_unweighted <- itd_cov_unw_tbl %>% left_join(precip_itd, by = "year")

# =============================================================================
# SECTION 8 — Plot aesthetics
# =============================================================================

col_vals   <- c(Reserve = "#2C7C4D", Fragment = "#BDBDBD")
shape_vals <- c(Reserve = 15,        Fragment = 16)

theme_panel <- theme_classic(base_size = 13) +
  theme(legend.position    = "right",
        axis.title.y       = element_text(margin = margin(r = 10)),
        axis.title.x       = element_text(margin = margin(t = 8)))

p_stars <- function(p) {
  if (is.na(p)) "n.s."
  else if (p < 0.001) "***"
  else if (p < 0.01)  "**"
  else if (p < 0.05)  "*"
  else if (p < 0.1)   "."
  else "n.s."
}

get_p_from_anova <- function(anova_tbl, term) {
  as.numeric(anova_tbl[term, "Pr(>Chisq)"])
}

annotate_tp <- function(anova_tbl,
                        precip_term = c("previous1_c", "same_c")) {
  precip_term <- match.arg(precip_term)
  paste0("T: ", p_stars(get_p_from_anova(anova_tbl, "Type")),
         "\nP: ", p_stars(get_p_from_anova(anova_tbl, precip_term)))
}

# =============================================================================
# SECTION 9 — Model functions
# =============================================================================

# 9a) Interaction models: Type × precip (MAIN analysis)
fit_itd_models_interaction <- function(df, response) {

  df_mod <- df %>%
    drop_na(.data[[response]], Plot, Type, same_c, previous1_c) %>%
    mutate(
      Type = fct_relevel(factor(Type), "Reserve", "Fragment"),
      Plot = factor(Plot),
      response_log = log(.data[[response]])
    )

  m_full_reml    <- lmer(reformulate(c("Type * previous1_c", "Type * same_c", "(1|Plot)"),
                                     response = "response_log"), data = df_mod, REML = TRUE)
  m_no_prev_reml <- lmer(reformulate(c("Type * same_c",      "(1|Plot)"),
                                     response = "response_log"), data = df_mod, REML = TRUE)
  m_no_same_reml <- lmer(reformulate(c("Type * previous1_c", "(1|Plot)"),
                                     response = "response_log"), data = df_mod, REML = TRUE)
  m_base_reml    <- lmer(reformulate(c("Type",               "(1|Plot)"),
                                     response = "response_log"), data = df_mod, REML = TRUE)

  m_full_ml    <- update(m_full_reml,    REML = FALSE)
  m_no_prev_ml <- update(m_no_prev_reml, REML = FALSE)
  m_no_same_ml <- update(m_no_same_reml, REML = FALSE)
  m_base_ml    <- update(m_base_reml,    REML = FALSE)

  r2_full    <- performance::r2_nakagawa(m_full_reml)
  r2_no_prev <- performance::r2_nakagawa(m_no_prev_reml)
  r2_no_same <- performance::r2_nakagawa(m_no_same_reml)
  r2_base    <- performance::r2_nakagawa(m_base_reml)

  list(
    data        = df_mod,
    models_reml = list(full = m_full_reml, no_prev = m_no_prev_reml,
                       no_same = m_no_same_reml, base = m_base_reml),
    models_ml   = list(full = m_full_ml,   no_prev = m_no_prev_ml,
                       no_same = m_no_same_ml,   base = m_base_ml),
    anova_full     = car::Anova(m_full_reml,    type = 3),
    lrt_drop_prev  = anova(m_full_ml, m_no_prev_ml),
    lrt_drop_same  = anova(m_full_ml, m_no_same_ml),
    aic = AIC(m_full_ml, m_no_prev_ml, m_no_same_ml, m_base_ml) %>%
      as.data.frame() %>% rownames_to_column("Model") %>% arrange(AIC),
    r2 = list(full = r2_full, no_prev = r2_no_prev,
              no_same = r2_no_same, base = r2_base),
    delta_marginal = tibble(
      term_dropped      = c("Type:previous1_c", "Type:same_c"),
      delta_R2_marginal = c(r2_full$R2_marginal - r2_no_prev$R2_marginal,
                            r2_full$R2_marginal - r2_no_same$R2_marginal)
    )
  )
}

# 9b) Additive models: no interactions (sensitivity)
fit_itd_models_additive <- function(df, response) {

  df_mod <- df %>%
    drop_na(.data[[response]], Plot, Type, same_c, previous1_c) %>%
    mutate(Type = fct_relevel(factor(Type), "Reserve", "Fragment"),
           Plot = factor(Plot),
           response_log = log(.data[[response]]))

  m_full_reml    <- lmer(reformulate(c("Type", "previous1_c", "same_c", "(1|Plot)"),
                                     response = "response_log"), data = df_mod, REML = TRUE)
  m_no_prev_reml <- lmer(reformulate(c("Type", "same_c",      "(1|Plot)"),
                                     response = "response_log"), data = df_mod, REML = TRUE)
  m_no_same_reml <- lmer(reformulate(c("Type", "previous1_c", "(1|Plot)"),
                                     response = "response_log"), data = df_mod, REML = TRUE)
  m_base_reml    <- lmer(reformulate(c("Type",                "(1|Plot)"),
                                     response = "response_log"), data = df_mod, REML = TRUE)

  m_full_ml    <- update(m_full_reml,    REML = FALSE)
  m_no_prev_ml <- update(m_no_prev_reml, REML = FALSE)
  m_no_same_ml <- update(m_no_same_reml, REML = FALSE)
  m_base_ml    <- update(m_base_reml,    REML = FALSE)

  r2_full    <- performance::r2_nakagawa(m_full_reml)
  r2_no_prev <- performance::r2_nakagawa(m_no_prev_reml)
  r2_no_same <- performance::r2_nakagawa(m_no_same_reml)
  r2_base    <- performance::r2_nakagawa(m_base_reml)

  list(
    data        = df_mod,
    models_reml = list(full = m_full_reml, no_prev = m_no_prev_reml,
                       no_same = m_no_same_reml, base = m_base_reml),
    models_ml   = list(full = m_full_ml,   no_prev = m_no_prev_ml,
                       no_same = m_no_same_ml,   base = m_base_ml),
    anova_full    = car::Anova(m_full_reml,    type = 3),
    lrt_drop_prev = anova(m_full_ml, m_no_prev_ml),
    lrt_drop_same = anova(m_full_ml, m_no_same_ml),
    aic = AIC(m_full_ml, m_no_prev_ml, m_no_same_ml, m_base_ml) %>%
      as.data.frame() %>% rownames_to_column("Model") %>% arrange(AIC),
    r2 = list(full = r2_full, no_prev = r2_no_prev,
              no_same = r2_no_same, base = r2_base),
    delta_marginal = tibble(
      term_dropped      = c("previous1_c", "same_c"),
      delta_R2_marginal = c(r2_full$R2_marginal - r2_no_prev$R2_marginal,
                            r2_full$R2_marginal - r2_no_same$R2_marginal)
    )
  )
}

# 9c) Type-split models: no Type term (supplement)
fit_itd_models_notype <- function(df, response) {

  df_mod <- df %>%
    drop_na(.data[[response]], Plot, same_c, previous1_c) %>%
    mutate(Plot = factor(Plot),
           response_log = log(.data[[response]]))

  m_full_reml    <- lmer(reformulate(c("previous1_c", "same_c", "(1|Plot)"),
                                     response = "response_log"), data = df_mod, REML = TRUE)
  m_no_prev_reml <- lmer(reformulate(c("same_c",      "(1|Plot)"),
                                     response = "response_log"), data = df_mod, REML = TRUE)
  m_no_same_reml <- lmer(reformulate(c("previous1_c", "(1|Plot)"),
                                     response = "response_log"), data = df_mod, REML = TRUE)
  m_base_reml    <- lmer(reformulate(c("(1|Plot)"),
                                     response = "response_log"), data = df_mod, REML = TRUE)

  m_full_ml    <- update(m_full_reml,    REML = FALSE)
  m_no_prev_ml <- update(m_no_prev_reml, REML = FALSE)
  m_no_same_ml <- update(m_no_same_reml, REML = FALSE)
  m_base_ml    <- update(m_base_reml,    REML = FALSE)

  r2_full    <- performance::r2_nakagawa(m_full_reml)
  r2_no_prev <- performance::r2_nakagawa(m_no_prev_reml)
  r2_no_same <- performance::r2_nakagawa(m_no_same_reml)
  r2_base    <- performance::r2_nakagawa(m_base_reml)

  list(
    data        = df_mod,
    models_reml = list(full = m_full_reml, no_prev = m_no_prev_reml,
                       no_same = m_no_same_reml, base = m_base_reml),
    models_ml   = list(full = m_full_ml,   no_prev = m_no_prev_ml,
                       no_same = m_no_same_ml,   base = m_base_ml),
    anova_full    = car::Anova(m_full_reml,    type = 3),
    lrt_drop_prev = anova(m_full_ml, m_no_prev_ml),
    lrt_drop_same = anova(m_full_ml, m_no_same_ml),
    aic = AIC(m_full_ml, m_no_prev_ml, m_no_same_ml, m_base_ml) %>%
      as.data.frame() %>% rownames_to_column("Model") %>% arrange(AIC),
    r2 = list(full = r2_full, no_prev = r2_no_prev,
              no_same = r2_no_same, base = r2_base),
    delta_marginal = tibble(
      term_dropped      = c("previous1_c", "same_c"),
      delta_R2_marginal = c(r2_full$R2_marginal - r2_no_prev$R2_marginal,
                            r2_full$R2_marginal - r2_no_same$R2_marginal)
    )
  )
}

# =============================================================================
# SECTION 10 — Fit models
# =============================================================================

cat("Fitting interaction models (weighted)...\n")
itd_fit_int     <- fit_itd_models_interaction(itd_weighted,   "avg_itd_cov")
cat("Fitting interaction models (unweighted)...\n")
itd_fit_int_uw  <- fit_itd_models_interaction(itd_unweighted, "avg_itd_cov_unw")

cat("Fitting additive models (weighted)...\n")
itd_fit_add     <- fit_itd_models_additive(itd_weighted,   "avg_itd_cov")
cat("Fitting additive models (unweighted)...\n")
itd_fit_add_uw  <- fit_itd_models_additive(itd_unweighted, "avg_itd_cov_unw")

# Type-split
itd_weighted_res    <- itd_weighted   %>% filter(Type == "Reserve")
itd_weighted_frag   <- itd_weighted   %>% filter(Type == "Fragment")
itd_unweighted_res  <- itd_unweighted %>% filter(Type == "Reserve")
itd_unweighted_frag <- itd_unweighted %>% filter(Type == "Fragment")

# Note: type-split models may produce singular fits (random effect variance = 0)
# because splitting by habitat type reduces within-plot replication substantially.
# Fixed effect estimates remain valid; R² values should be interpreted with caution.
# These analyses are reported in the supplementary materials.
itd_fit_res      <- fit_itd_models_notype(itd_weighted_res,    "avg_itd_cov")
itd_fit_frag     <- fit_itd_models_notype(itd_weighted_frag,   "avg_itd_cov")
itd_fit_res_uw   <- fit_itd_models_notype(itd_unweighted_res,  "avg_itd_cov_unw")
itd_fit_frag_uw  <- fit_itd_models_notype(itd_unweighted_frag, "avg_itd_cov_unw")

# =============================================================================
# SECTION 11 — Print key results (interaction models = main analysis)
# =============================================================================

cat("\n=== WEIGHTED — interaction model ===\n")
itd_fit_int$anova_full
summary(itd_fit_int$models_reml$full)
itd_fit_int$r2$full
itd_fit_int$delta_marginal
itd_fit_int$lrt_drop_prev
itd_fit_int$lrt_drop_same
itd_fit_int$aic

cat("\n=== UNWEIGHTED — interaction model ===\n")
itd_fit_int_uw$anova_full
summary(itd_fit_int_uw$models_reml$full)
itd_fit_int_uw$r2$full
itd_fit_int_uw$delta_marginal
itd_fit_int_uw$lrt_drop_prev
itd_fit_int_uw$lrt_drop_same
itd_fit_int_uw$aic

cat("\n=== TYPE-SPLIT — reserves weighted ===\n")
itd_fit_res$anova_full; itd_fit_res$r2$full; itd_fit_res$aic

cat("\n=== TYPE-SPLIT — fragments weighted ===\n")
itd_fit_frag$anova_full; itd_fit_frag$r2$full; itd_fit_frag$aic

# =============================================================================
# SECTION 12 — Figures
# =============================================================================

# Weighted
lab_prev_w <- annotate_tp(itd_fit_int$anova_full, "previous1_c")
lab_same_w <- annotate_tp(itd_fit_int$anova_full, "same_c")

p_itd_prev <- ggplot(itd_weighted, aes(x = previous1, y = avg_itd_cov)) +
  geom_point(aes(color = Type, shape = Type), alpha = 0.3, size = 2) +
  geom_smooth(aes(color = Type, fill = Type),
              method = "lm", formula = y ~ x, se = TRUE,
              linewidth = 1.2, alpha = 0.25) +
  scale_color_manual(values = col_vals, guide = "none") +
  scale_fill_manual(values  = col_vals, guide = "none") +
  scale_shape_manual(values = shape_vals, guide = "none") +
  labs(x = "Previous-year winter precipitation (mm)",
       y = "Assemblage-weighted mean ITD (mm)") +
  theme_panel

p_itd_same <- ggplot(itd_weighted, aes(x = same, y = avg_itd_cov)) +
  geom_point(aes(color = Type, shape = Type), alpha = 0.3, size = 2) +
  geom_smooth(aes(color = Type, fill = Type),
              method = "lm", formula = y ~ x, se = TRUE,
              linewidth = 1.2, alpha = 0.25) +
  scale_color_manual(values = col_vals, guide = "none") +
  scale_fill_manual(values  = col_vals, guide = "none") +
  scale_shape_manual(values = shape_vals, guide = "none") +
  labs(x = "Same-year winter precipitation (mm)", y = NULL) +
  theme_panel

p_itd_model <- p_itd_prev + p_itd_same + plot_layout(ncol = 2)
print(p_itd_model)
ggsave(file.path(figures_dir, "itd_weighted_model.svg"),
       p_itd_model, width = 10, height = 4, units = "in")

# Unweighted
p_itd_unw_prev <- ggplot(itd_unweighted, aes(x = previous1, y = avg_itd_cov_unw)) +
  geom_point(aes(color = Type, shape = Type), alpha = 0.3, size = 2) +
  geom_smooth(aes(color = Type, fill = Type),
              method = "lm", formula = y ~ x, se = TRUE,
              linewidth = 1.2, alpha = 0.25) +
  scale_color_manual(values = col_vals, guide = "none") +
  scale_fill_manual(values  = col_vals, guide = "none") +
  scale_shape_manual(values = shape_vals, guide = "none") +
  labs(x = "Previous-year winter precipitation (mm)",
       y = "Assemblage-unweighted mean ITD (mm)") +
  theme_panel

p_itd_unw_same <- ggplot(itd_unweighted, aes(x = same, y = avg_itd_cov_unw)) +
  geom_point(aes(color = Type, shape = Type), alpha = 0.3, size = 2) +
  geom_smooth(aes(color = Type, fill = Type),
              method = "lm", formula = y ~ x, se = TRUE,
              linewidth = 1.2, alpha = 0.25) +
  scale_color_manual(values = col_vals, guide = "none") +
  scale_fill_manual(values  = col_vals, guide = "none") +
  scale_shape_manual(values = shape_vals, guide = "none") +
  labs(x = "Same-year winter precipitation (mm)", y = NULL) +
  theme_panel

p_itd_unw_model <- p_itd_unw_prev + p_itd_unw_same + plot_layout(ncol = 2)
print(p_itd_unw_model)
ggsave(file.path(figures_dir, "itd_unweighted_model.svg"),
       p_itd_unw_model, width = 10, height = 4, units = "in")

# =============================================================================
# SECTION 13 — DHARMa diagnostics (matches R-05 approach)
#
# Runs on the main weighted and unweighted interaction models.
# Box-Cox lambda, simulated residuals, dispersion, outlier, uniformity tests.
# =============================================================================

run_diagnostics_itd <- function(model, metric_name, diag_dat) {

  diag_dat <- as.data.frame(diag_dat)

  cat("\n==============================\n")
  cat("Diagnostics:", metric_name, "\n")
  cat("==============================\n")

  # ---- 1) Box-Cox ----
  y       <- diag_dat[["Value"]]
  lambdas <- seq(-2, 2, by = 0.1)
  log_liks <- sapply(lambdas, function(lam) {
    y_t <- if (abs(lam) < 1e-10) log(y) else (y^lam - 1) / lam
    sum(dnorm(y_t, mean(y_t), sd(y_t), log = TRUE)) + (lam - 1) * sum(log(y))
  })
  lambda_opt <- lambdas[which.max(log_liks)]
  cat("Box-Cox optimal lambda:", round(lambda_opt, 3),
      " (log = 0, no transform = 1)\n")

  # ---- 2) Distribution check ----
  png(file.path(figures_dir, "diagnostics",
                paste0(metric_name, "_distribution_check.png")),
      width = 800, height = 400, res = 120)
  par(mfrow = c(1, 2))
  hist(diag_dat[["Value"]], main = paste(metric_name, "- raw"),
       xlab = "Value", col = "steelblue", border = "white")
  hist(log(diag_dat[["Value"]] + 0.001), main = paste(metric_name, "- log"),
       xlab = "log(Value)", col = "coral", border = "white")
  par(mfrow = c(1, 1))
  dev.off()

  # ---- 3) DHARMa ----
  sim_res      <- DHARMa::simulateResiduals(model, n = 1000, plot = FALSE)
  disp_test    <- DHARMa::testDispersion(sim_res,  plot = FALSE)
  outlier_test <- DHARMa::testOutliers(sim_res,    plot = FALSE)
  unif_test    <- DHARMa::testUniformity(sim_res,  plot = FALSE)

  png(file.path(figures_dir, "diagnostics",
                paste0(metric_name, "_dharma_residuals.png")),
      width = 900, height = 500, res = 120)
  plot(sim_res, main = metric_name)
  dev.off()

  cat("DHARMa dispersion p =", round(disp_test$p.value,    4), "\n")
  cat("DHARMa outlier p =",    round(outlier_test$p.value, 4), "\n")
  cat("DHARMa uniformity p =", round(unif_test$p.value,    4), "\n")

  # ---- 4) check_model ----
  perf_plot <- performance::check_model(model)
  ggplot2::ggsave(
    file.path(figures_dir, "diagnostics",
              paste0(metric_name, "_check_model.png")),
    plot = plot(perf_plot), width = 12, height = 10, dpi = 150
  )

  tibble::tibble(
    metric           = metric_name,
    boxcox_lambda    = round(lambda_opt,           3),
    dharma_disp_p    = round(disp_test$p.value,    4),
    dharma_outlier_p = round(outlier_test$p.value, 4),
    dharma_uniform_p = round(unif_test$p.value,    4)
  )
}

# Prepare data frames with a "Value" column for the diagnostics function
dd_weighted   <- itd_fit_int$data    %>% rename(Value = avg_itd_cov)
dd_unweighted <- itd_fit_int_uw$data %>% rename(Value = avg_itd_cov_unw)

diag_w  <- run_diagnostics_itd(itd_fit_int$models_reml$full,
                                "ITD_weighted",   dd_weighted)
diag_uw <- run_diagnostics_itd(itd_fit_int_uw$models_reml$full,
                                "ITD_unweighted", dd_unweighted)

diag_summary_itd <- bind_rows(diag_w, diag_uw)
print(diag_summary_itd)

writexl::write_xlsx(diag_summary_itd,
                    file.path(results_dir, "diagnostics_dharma_itd.xlsx"))

cat("\nDiagnostic plots saved to figures/diagnostics/\n")

# =============================================================================
# SECTION 14 — Export model results
# =============================================================================

tidy_fit <- function(fit, label) {
  tibble(
    model        = label,
    term         = rownames(fit$anova_full),
    Chisq        = fit$anova_full[, "Chisq"],
    Df           = fit$anova_full[, "Df"],
    p_value      = fit$anova_full[, "Pr(>Chisq)"],
    R2_marginal  = fit$r2$full$R2_marginal,
    R2_conditional = fit$r2$full$R2_conditional
  )
}

results_tbl <- bind_rows(
  tidy_fit(itd_fit_int,    "weighted_interaction"),
  tidy_fit(itd_fit_int_uw, "unweighted_interaction"),
  tidy_fit(itd_fit_add,    "weighted_additive"),
  tidy_fit(itd_fit_add_uw, "unweighted_additive"),
  tidy_fit(itd_fit_res,    "reserves_only"),
  tidy_fit(itd_fit_frag,   "fragments_only"),
  tidy_fit(itd_fit_res_uw, "reserves_only_unweighted"),
  tidy_fit(itd_fit_frag_uw,"fragments_only_unweighted")
)

aic_tbl <- bind_rows(
  itd_fit_int$aic     %>% mutate(model = "weighted_interaction",   .before = 1),
  itd_fit_int_uw$aic  %>% mutate(model = "unweighted_interaction", .before = 1),
  itd_fit_add$aic     %>% mutate(model = "weighted_additive",      .before = 1),
  itd_fit_add_uw$aic  %>% mutate(model = "unweighted_additive",    .before = 1)
)

delta_tbl <- bind_rows(
  itd_fit_int$delta_marginal    %>% mutate(model = "weighted_interaction",   .before = 1),
  itd_fit_int_uw$delta_marginal %>% mutate(model = "unweighted_interaction", .before = 1),
  itd_fit_add$delta_marginal    %>% mutate(model = "weighted_additive",      .before = 1),
  itd_fit_add_uw$delta_marginal %>% mutate(model = "unweighted_additive",    .before = 1)
)

writexl::write_xlsx(
  list(
    ANOVA_results  = results_tbl,
    AIC_comparison = aic_tbl,
    Delta_R2       = delta_tbl
  ),
  file.path(results_dir, "ITD_model_results.xlsx")
)

message("\n--- Body size analysis complete ---")
message("Figures written to: ", figures_dir)
message("Results written to: ", results_dir)

